<script type="text/javascript">
    var lang = new Object();
        lang.moduleInstall = "{lang('Module installed','admin')}";
        lang.moduleSuccessInstall = "{lang('Module successfully installed','admin')}";
        lang.error = "{lang('Error','admin')}";
        lang.errorSomethingWereWrong = "{lang('Something went wrong. Startup status is not changed.')}";
        lang.errorUrlAccess = "{lang('Something went wrong. URL access is not changed.')}";
        lang.turnOn = "{lang('Turn on','admin')}";
        lang.turnOff = "{lang('Turn off','admin')}";
        lang.haveNotModulesToInstall = "{lang('Have not modules to install','admin')}";
        lang.creatingWidget = "{lang('Widget creating','admin')}";
        lang.createdSuccessfullyWidget = "{lang('Widget successfully created','admin')}";
        lang.deleteGroup = "{lang('Delete group','admin')}";
        lang.enterTemplateName = "{lang('Enter template name','admin')}";
        lang.categoryHaveNotPage = "{lang('No pages in category','admin')}";
        lang.categorySuccessfullyAdd = "{lang('Category successfully added','admin')}";
        lang.name = "{lang('Name','admin')}";
        lang.discount = "{lang('Discount','admin')}";
        lang.needToEnterName = "{lang('You need to enter a string','admin')}";
        lang.needToFillField = "{lang('This field is required.','admin')}";
        lang.please = "{lang('Please','admin')}";
        lang.enterCorrectValue = "{lang('enter the correct value','admin')}";
        lang.enterValidEmailAddress = "{lang('enter a valid email address','admin')}";
        lang.enterCorrectURL = "{lang('enter the correct URL','admin')}";
        lang.enterCorrectDate = "{lang('enter correct date','admin')}";
        lang.enterCorrectDateFormatISO= "{lang('enter correct date in format ISO','admin')}";
        lang.enterNumber = "{lang('enter number','admin')}";
        lang.enterOnlyNumbers = "{lang('enter only numbers','admin')}";
        lang.enterValidCreditCardNumber = "{lang('enter a valid credit card number','admin')}";
        lang.enterTheSameValueAgain = "{lang('enter the same value again','admin')}";
        lang.selectFileWwithCorrectExtension = "{lang('Select the file with the correct extension','admin')}";
        lang.enterNoMore = "{lang('Enter no more','admin')}";
        lang.characters = "{lang('characters','admin')}";
        lang.enterAtLeast = "{lang('enter at least','admin')}";
        lang.enterValueFrom = "{lang('enter value from','admin')}";
        lang.to = "{lang('to','admin')}";
        lang.enterNumberFrom = "{lang('enter number from','admin')}";
        lang.enterNumberLessThanOrEqualTo = "{lang('enter a number less than or equal to','admin')}";
        lang.enterNumberMoreThanOrEqualTo = "{lang('enter a number more than or equal to','admin')}";
        // shop module
        lang.administrateShop = "{lang('Administer shop','admin')}";
        lang.backToTheSystem = "{lang('Back to the system','admin')}";
        lang.errorConversion = "{lang('Conversion error','admin')}";
        lang.userAlreadyNotifiedViaEmail = "{lang('User already notified via E-mail upon availability! Notify again')}";
        lang.notifyUserViaEmailUponAvailability = "{lang('Notify the user via E-mail upon availability')}";
        lang.errorOptionsRemoving = "{lang('Error removing options','admin')}";
        lang.deleteCanceledOrders = "{lang('Delete canceled orders','admin')}";
        lang.deleteCanceledMessages = "{lang('Delete canceled messages','admin')}";
        lang.deleteOredrID =  "{lang('Delete order ID','admin')}";
        lang.productChanges = "{lang('Product changes','admin')}";
        lang.success = "{lang('Success','admin')}";
        lang.fileIsLoadedSlot = "{lang('File is loaded. Slot')}";
        lang.scriptErrorNotifyAdministrator = "{lang('Script error. Notify administrator.')}";
        lang.waitForResizeEnding = "{lang('Wait for resize ending','admin')}";
        lang.resizeImagesForProducts = "{lang('Resize images for products','admin')}";
        lang.allFindingProducts = "{lang('All finding products','admin')}";
        lang.processed = "{lang('Processed','admin')}";
        lang.imagesUpdated = "{lang('Images updated','admin')}";
        lang.completed = "{lang('Completed','admin')}";
        
</script>

    