<?php

namespace mod_discount\classes;

require_once realpath(dirname(__FILE__) . '/../..') . '/enviroment.php';

doLogin();

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-02 at 10:45:08.
 */
class BaseDiscountTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BaseDiscount
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BaseDiscount();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers mod_discount\classes\BaseDiscount::check_module_install
     */
    public function testCheck_module_install() {
        $this->assertTrue($this->object->check_module_install());
    }

    /**
     * @covers mod_discount\classes\BaseDiscount::get_user_id
     * @todo   Implement testGet_user_id().
     */
    public function testGet_user_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mod_discount\classes\BaseDiscount::get_user_group_id
     * @todo   Implement testGet_user_group_id().
     */
    public function testGet_user_group_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mod_discount\classes\BaseDiscount::get_cart_data
     * @todo   Implement testGet_cart_data().
     */
    public function testGet_cart_data() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mod_discount\classes\BaseDiscount::get_amout_user
     * @todo   Implement testGet_amout_user().
     */
    public function testGet_amout_user() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mod_discount\classes\BaseDiscount::get_total_price
     * @todo   Implement testGet_total_price().
     */
    public function testGet_total_price() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mod_discount\classes\BaseDiscount::get_all_discount
     * @todo   Implement testGet_all_discount().
     */
    public function testGet_all_discount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mod_discount\classes\BaseDiscount::collect_type
     * @todo   Implement testCollect_type().
     */
    public function testCollect_type() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mod_discount\classes\BaseDiscount::get_max_discount
     * @todo   Implement testGet_max_discount().
     */
    public function testGet_max_discount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mod_discount\classes\BaseDiscount::get_discount_value
     * @todo   Implement testGet_discount_value().
     */
    public function testGet_discount_value() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mod_discount\classes\BaseDiscount::updatediskapply
     * @todo   Implement testUpdatediskapply().
     */
    public function testUpdatediskapply() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
