<?php
namespace comment;

require_once realpath(dirname(__FILE__) . '/../..') . '/enviroment.php';

doLogin();
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-02 at 11:06:25.
 */
class CommentsapiTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Commentsapi
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Commentsapi;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Commentsapi::renderPosts
     * @todo   Implement testRenderPosts().
     */
    public function testRenderPosts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Commentsapi::parsUrl
     * @todo   Implement testParsUrl().
     */
    public function testParsUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Commentsapi::getModule
     * @todo   Implement testGetModule().
     */
    public function testGetModule() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Commentsapi::newPost
     * @todo   Implement testNewPost().
     */
    public function testNewPost() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Commentsapi::setyes
     * @todo   Implement testSetyes().
     */
    public function testSetyes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Commentsapi::setno
     * @todo   Implement testSetno().
     */
    public function testSetno() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Commentsapi::captcha_check
     * @todo   Implement testCaptcha_check().
     */
    public function testCaptcha_check() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Commentsapi::get_comments_number
     * @todo   Implement testGet_comments_number().
     */
    public function testGet_comments_number() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Commentsapi::getTotalCommentsForProducts
     * @todo   Implement testGetTotalCommentsForProducts().
     */
    public function testGetTotalCommentsForProducts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Commentsapi::Pluralize
     * @todo   Implement testPluralize().
     */
    public function testPluralize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
