<?php

require_once realpath(dirname(__FILE__) . '/../..') . '/enviroment.php';

doLogin();

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-27 at 13:30:04.
 */
class Wishlist_modelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Wishlist_model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Wishlist_model;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Wishlist_model::getSettings
     * @todo   Implement testGetSettings().
     */
    public function testGetSettings() {
        $this->assertNotNull($this->object->getSettings(), 'Cant get Settings');
        $this->assertArrayHasKey('maxListName', $this->object->getSettings());
        $this->assertArrayHasKey('maxListsCount', $this->object->getSettings());
        $this->assertArrayHasKey('maxItemsCount', $this->object->getSettings());
        $this->assertArrayHasKey('maxCommentLenght', $this->object->getSettings());
        $this->assertArrayHasKey('maxDescLenght', $this->object->getSettings());
        $this->assertArrayHasKey('maxImageWidth', $this->object->getSettings());
        $this->assertArrayHasKey('maxImageHeight', $this->object->getSettings());
    }

    /**
     * @covers Wishlist_model::setSettings
     * @todo   Implement testSetSettings().
     */
    public function testSetSettings() {
        $settings =
                array(
                    'maxListName' => 254,
                    'maxListsCount' => 10,
                    'maxItemsCount' => 100,
                    'maxCommentLenght' => 500,
                    'maxDescLenght' => 1000,
                    'maxImageWidth' => 150,
                    'maxImageHeight' => 150);
        $this->assertTrue($this->object->setSettings($settings), 'Cant Set Settings');
    }

    /**
     * @covers Wishlist_model::getWishLists
     * @todo   Implement testGetWishLists().
     */
    public function testGetWishLists() {
        $this->object->getWishLists($GLOBALS['userId']);
    }

    /**
     * @covers Wishlist_model::getAllUsers
     * @todo   Implement testGetAllUsers().
     */
    public function testGetAllUsers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::getUserByID
     * @todo   Implement testGetUserByID().
     */
    public function testGetUserByID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::getWLsByUserId
     * @todo   Implement testGetWLsByUserId().
     */
    public function testGetWLsByUserId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::getUserWishList
     * @todo   Implement testGetUserWishList().
     */
    public function testGetUserWishList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::deleteItem
     * @todo   Implement testDeleteItem().
     */
    public function testDeleteItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::deleteItemsByIDs
     * @todo   Implement testDeleteItemsByIDs().
     */
    public function testDeleteItemsByIDs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::getUserWishListsByID
     * @todo   Implement testGetUserWishListsByID().
     */
    public function testGetUserWishListsByID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::delWishListById
     * @todo   Implement testDelWishListById().
     */
    public function testDelWishListById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::delWishListProductsByWLId
     * @todo   Implement testDelWishListProductsByWLId().
     */
    public function testDelWishListProductsByWLId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::getUserWishProducts
     * @todo   Implement testGetUserWishProducts().
     */
    public function testGetUserWishProducts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::getMostPopularProducts
     * @todo   Implement testGetMostPopularProducts().
     */
    public function testGetMostPopularProducts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::insertWishList
     * @todo   Implement testInsertWishList().
     */
    public function testInsertWishList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::upateWishList
     * @todo   Implement testUpateWishList().
     */
    public function testUpateWishList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::upateWishListItemsComments
     * @todo   Implement testUpateWishListItemsComments().
     */
    public function testUpateWishListItemsComments() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::insertUser
     * @todo   Implement testInsertUser().
     */
    public function testInsertUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::addItem
     * @todo   Implement testAddItem().
     */
    public function testAddItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::createUserIfNotExist
     * @todo   Implement testCreateUserIfNotExist().
     */
    public function testCreateUserIfNotExist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::updateUser
     * @todo   Implement testUpdateUser().
     */
    public function testUpdateUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::createWishList
     * @todo   Implement testCreateWishList().
     */
    public function testCreateWishList() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->createWishList('adas', $GLOBALS['userId']));
    }

    /**
     * @covers Wishlist_model::getUserWishListCount
     * @todo   Implement testGetUserWishListCount().
     */
    public function testGetUserWishListCount() {
        $this->assertContainsOnly('int', array($this->object->getUserWishListCount($GLOBALS['userId'])));
    }

    /**
     * @covers Wishlist_model::getUserWishListItemsCount
     * @todo   Implement testGetUserWishListItemsCount().
     */
    public function testGetUserWishListItemsCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::addRewiew
     * @todo   Implement testAddRewiew().
     */
    public function testAddReview() {
//        $this->testAddItem();
//        $this->assertTrue($this->object->addReview(''), 'Cant add review');
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::getMostViewedWishLists
     * @todo   Implement testGetMostViewedWishLists().
     */
    public function testGetMostViewedWishLists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wishlist_model::deinstall
     * @todo   Implement testDeinstall().
     */
    public function testDeinstall() {
        $this->assertTrue($this->object->deinstall(), 'Cant deinstall');
    }

    /**
     * @covers Wishlist_model::install
     * @todo   Implement testInstall().
     */
    public function testInstall() {
        $this->assertTrue($this->object->install(), 'Cant install');
    }

}
