<?php

require_once realpath(dirname(__FILE__) . '/../../..') . '/enviroment.php';
require_once APPPATH . 'modules/' . getModContDirName('mod_discount') . '/mod_discount/admin.php';
doLogin();

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-03 at 13:11:06.
 */
class AdminTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Admin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Admin();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Prepare test data
     * @covers Admin::all
     */
    public function testPrepareTestData() {
        $this->_prepareData();
    }

    /**
     * @covers Admin::ajaxChangeActive
     * @dataProvider changeActiveParametrs
     */
    public function testAjaxChangeActive($id, $param) {
        $_POST['id'] = $id;
        $this->expectOutputString($param);
        $this->object->ajaxChangeActive();
    }

    public function changeActiveParametrs() {
        return array(
            array(1, '1'),
            array(111, ''),
            array(1.234, ''),
            array('asdfgh', ''),
            array('', '')
        );
    }

    /**
     * @covers Admin::ajaxDeleteDiscount
     * @dataProvider deleteDiscountParametrs
     */
    public function testAjaxDeleteDiscount($id, $param) {
        $_POST['id'] = $id;
        $this->expectOutputString($param);
        $this->object->ajaxDeleteDiscount();
    }

    public function deleteDiscountParametrs() {
        return array(
            array(1, '1'),
            array(111, ''),
            array(111, ''),
            array(1.234, ''),
            array('asdfgh', ''),
            array('')
        );
    }

    /**
     * @covers Admin::generateDiscountKey
     * @todo   Implement testGenerateDiscountKey().
     */
    public function testGenerateDiscountKey() {
        $result = $this->object->generateDiscountKey();
        $this->assertInternalType('string', $result);
        $this->assertEquals(16, strlen($result));
    }

    /**
     * @covers Admin::autoCompliteUsers
     * @todo   Implement testAutoCompliteUsers().
     */
    public function testAutoCompliteUsers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Admin::autoCompliteProducts
     * @todo   Implement testAutoCompliteProducts().
     */
    public function testAutoCompliteProducts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Admin::saveQueryToSession
     * @todo   Implement testSaveQueryToSession().
     */
    public function testSaveQueryToSession() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * Prepare data for tests. Install/Deinstall and insert testing values
     */
    private function _prepareData() {
        $this->object->discount_model_admin->moduleDelete();
        $this->object->discount_model_admin->moduleInstall();
        $sql = "INSERT INTO `mod_shop_discounts` (`id`, `key`, `name`, `active`, `max_apply`,
                `count_apply`, `date_begin`, `date_end`, `type_value`, `value`, `type_discount`)
                VALUES (1, '87046de8c6hzy2kl', 'test', 1, NULL, NULL, 1372795200, 0, 1, 
                50, 'user');";
        $this->object->db->query($sql);
        $sql2 = "INSERT INTO `image`.`mod_discount_user` (`id`, `user_id`, `discount_id`)
                VALUES ('1', '1', '1');";
        $this->object->db->query($sql2);
    }

}
