languages:
  JavaScript: true
  PHP: true

exclude_paths:
- "system/**"
- "application/cms_bridge.php"
- "tests/**"
- "**/tests/**"
- "hooks/**"
- "application/libraries/elfinder/**"
- "js/**"
- "application/modules/translator/assets/js/**"
- "application/modules/admin_menu/menus/**"
- "**/generated-classes/Base/**"
- "**/generated-classes/Map/**"
- "**/generated-classes/**/Base/**"
- "**/generated-classes/**/Map/**"
- "Models/Base/**"
- "Models/Map/**"
- "application/third_party/**"
- "application/modules/banners/assets/js/cycle.js"
- "templates/**"
- "application/modules/egoods/assets/js/epub/**"
- "application/modules/sitetest/**"
- "application/modules/documentation/**"
- "application/modules/my_module_frame/**"
- "application/modules/egoods/assets/js/jwplayer/**"
- "application/modules/egoods/vendors/**"
- "application/modules/facebook_store/**"
- "application/modules/gallery/assets/js/jquery.mousewheel-3.0.4.pack.js"
- "application/modules/mod_stats/assets/js/nv.d3.js"
- "application/modules/mod_stats/assets/js/d3.v3.js"
- "application/modules/translate/**"
- "application/modules/shop/obf/**"
- "**/module_info.php"
- "**/vendor/**"
- "uploads_site/**"
