<?php
/*
../../../templates/administrator/./advanced_search.tpl
../../../templates/administrator/./translateRole.tpl
../../../templates/administrator/./languages.tpl
../../../templates/administrator/./widget_create.tpl
../../../templates/administrator/./inc/javascriptVars.tpl
../../../templates/administrator/./inc/jsLangs.tpl*/

_("Full description");
_("Delete language");
_("Delete selected languages?");
_("Attention! All pages in this language will be deleted!");
_("Delete");
_("Languages");
_("Create language");
_("Select the module type to the table below");
_("Module installed");
_("Module successfully installed");
_("Error");
_("Something went wrong. Startup status is not changed.");
_("Something went wrong. URL access is not changed.");
_("Turn on");
_("Turn off");
_("Have not modules to install");
_("Widget creating");
_("Widget successfully created");
_("Delete group");
_("Enter template name");
_("No pages in category");
_("Category successfully added");
_("Name");
_("Discount");
_("You need to enter a string");
_("This field is required.");
_("Please");
_("enter the correct value");
_("enter a valid email address");
_("enter the correct URL");
_("enter correct date");
_("enter correct date in format ISO");
_("enter number");
_("enter only numbers");
_("enter a valid credit card number");
_("enter the same value again");
_("Select the file with the correct extension");
_("Enter no more");
_("characters");
_("enter at least");
_("enter value from");
_("to");
_("enter number from");
_("enter a number less than or equal to");
_("enter a number more than or equal to");
_("Administer shop");
_("Back to the system");
_("Conversion error");
_("User already notified via E-mail upon availability! Notify again");
_("Notify the user via E-mail upon availability");
_("Error removing options");
_("Delete canceled orders");
_("Delete canceled messages");
_("Delete order ID");
_("Product changes");
_("Success");
_("File is loaded. Slot");
_("Script error. Notify administrator.");
_("Wait for resize ending");
_("Resize images for products");
_("All finding products");
_("Processed");
_("Images updated");
_("Completed");
_("Resize products images");
_("Products found");
_("Additional images resize");
_("Found products with additional images");
_("Images updated");
_("Access denied");
_("This is a demo version ImageCMS. Part of the actions are limited. For a complete functional download and install the distribution.");
_("Message");
_("Please enter the column number");
_("Column number updated");
_("Failed to update the column number");
_("Product");
_("Variant");
_("Price");
_("Balance");
_("Out of stock");
_("Add to Cart");
_("In the cart");
_("A user with this email already exists");
_("New user created");
_("Failed to create user");
_("Check the input data and fill in all mandatory fields");
_("Current certificate (amount):");
_("Sort method updated");
_("Manage shop");
_("Back to the system");
_("Conversion error, ");
_("Failure to remove variant");
_("Remove selected orders?");
_("Remove selected notifications?");
_("Remove order with ID: ");
_("Change product");
_("The file is loaded. Slot ");
_("Error in the script. Please notify the administrator");
_("This field is required");
_("Please fix this field.");
_("Enter a valid email address.");
_("Please enter a valid URL.");
_("Please enter a valid date.");
_("Please enter a valid date (ISO).");
_("Please enter a valid number.");
_("Please enter only digits.");
_("Please enter a valid credit card number.");
_("Please enter the same value again.");
_("Please enter a value with a valid extension.");
_("Please enter no more than {0} characters.");
_("Please enter at least {0} characters.");
_("Please enter a value between {0} and {1} characters long.");
_("Please enter a value between {0} and {1}.");
_("Please enter a value less than or equal to {0}.");
_("Please enter a value greater than or equal to {0}.");
_("Role edit");
_("Back");
_("Save");
_("Save and exit");
_("English");
_("Russian");
_("Russian");
_("English");
_("Properties");
_("Description");
_("Cancel");
_("Delete");
_("Name");
_("Folder");
_("Identifier");
_("Template");
_("Image");
_("by default");
_("Editing");
_("Widget creating");
_("Go back");
_("Create");
_("Save and go back");
_("Properties");
_("Name");
_("Description");
_("Short widget description");
_("Type");
_("Module");
_("HTML");
_("Module name");
_("Name");
_("Description");
_("Type");

?>