<?php
/*
../../modules/shop/admin/templates/comulativ/allusers.tpl
../../modules/shop/admin/templates/comulativ/edit.tpl
../../modules/shop/admin/templates/gifts/index.tpl
../../modules/shop/admin/templates/gifts/create.tpl
../../modules/shop/admin/templates/gifts/settings.tpl
../../modules/shop/admin/templates/gifts/edit.tpl
../../modules/shop/admin/templates/commulative/user.tpl
../../modules/shop/admin/templates/commulative/edit.tpl
../../modules/shop/admin/templates/discounts/autodrop.tpl
../../modules/shop/admin/templates/discounts/create.tpl
../../modules/shop/admin/templates/discounts/list.tpl
../../modules/shop/admin/templates/discounts/edit.tpl
../../modules/shop/admin/templates/users/create.tpl
../../modules/shop/admin/templates/users/list.tpl
../../modules/shop/admin/templates/users/edit_orders_list.tpl
../../modules/shop/admin/templates/users/edit.tpl*/

_("Deposit rates");
_("Back");
_("ID");
_("Full name");
_("E-mail");
_("Discount");
_("Date");
_("Empty user list.");
_("Editing discounts");
_("Back");
_("Have been saved");
_("Save and exit");
_("Discount options");
_("Member Discount");
_("Editing");
_("Discounts");
_("Discount");
_("Just like the number 10");
_("Active");
_("Discount");
_("from");
_("Discount");
_("to");
_("Name");
_("to");
_("ID");
_("Full name");
_("E-mail");
_("Address");
_("Telephone");
_("Date");
_("Removing Gift Certificate");
_("Remove selected gift certificates?");
_("Delete");
_("Cancel");
_("Removing Gift Certificate");
_("Remove a gift certificate?");
_("Gift certificate list");
_("Create gift certificate");
_("Settings");
_("Delete");
_("ID");
_("Unique key");
_("Price");
_("Has been created");
_("Valid to");
_("Active");
_("switch on");
_("switch off");
_("Gift certificate list is empty.");
_("Gift certificate create");
_("Back");
_("Create");
_("Create and exit");
_("Properties");
_("Gift certificate price");
_("Key");
_("Generate");
_("Active until");
_("Gift certificate settings");
_("Back");
_("Have been saved");
_("Save and go back");
_("Properties");
_("Use gift certificates?");
_("Gift certificate edit");
_("Back");
_("Have been saved");
_("Save and go back");
_("Properties");
_("Gift certificate price");
_("Key");
_("Active until");
_("Editing by discounts");
_("Back");
_("Have been saved");
_("Save and exit");
_("Data");
_("Full name");
_("E-mail");
_("Purchase price");
_("Discount");
_("Off manually entered");
_("Editing discounts");
_("Back");
_("Have been saved");
_("Save and exit");
_("Discount options");
_("Member Discount");
_("Editing");
_("Discounts");
_("Discount");
_("Just like the number 10");
_("Active");
_("Discount");
_("from");
_("Discount");
_("to");
_("Description");
_("ID");
_("Full name");
_("E-mail");
_("Address");
_("Telephone");
_("Date");
_("ID");
_("Full name");
_("E-mail");
_("Address");
_("Telephone");
_("Date");
_("This discount does not enjoy");
_("Create");
_("Discounts");
_("Back");
_("Create");
_("Save and exit");
_("Payment method create");
_("Name");
_("Active");
_("Description");
_("Starting date");
_("choose a date");
_("Finishing date ");
_("choose a date");
_("Discounts");
_(" Number greater than zero. To use a percent discount  apply : "SUM" format.");
_("Categories");
_("Enter a product for promotion");
_("Enter the name or id");
_("Selected products:");
_("Follow product ID by a comma.");
_("User group");
_("There are no translations users");
_("Unregistered users");
_("Close");
_("Removing discounts");
_("Remove selected discount?");
_("Delete");
_("Cancel");
_("Removing discounts");
_("Remove the discount?");
_("List of permanent discounts");
_("Deposit rates");
_("Create a discount");
_("Delete");
_("ID");
_("Name");
_("Starting date");
_("Finishing date ");
_("Active");
_("Editing");
_("Active");
_("Empty discount list");
_("Editing discounts");
_("Back");
_("Have been saved");
_("Save and exit");
_("Editing");
_("Discounts");
_("Name");
_("Active");
_("Description");
_("Starting date");
_("Finishing date ");
_("Discounts");
_(" Number greater than zero. To use a percent discount  apply : "SUM" format.");
_("Categories");
_("Enter a product for discount");
_("Enter the name or id");
_("Selected products:");
_("Follow product ID by a comma.");
_("User group");
_("There are no translations users");
_("Unregistered users");
_("Create user");
_("Back");
_("Create");
_("Save and exit");
_("Data");
_("E-mail");
_("Password");
_("Role");
_("Full name");
_("Telephone");
_("Address");
_("Additional data");
_("Deleting a user");
_("Remove selected users?");
_("Delete");
_("Cancel");
_("Deleting a user");
_("Deleting a user");
_("Users list");
_("Filter");
_("Cancel filter");
_("Cancel filter");
_("Create user");
_("Delete");
_("User");
_("Export");
_("ID");
_("E-mail");
_("User");
_("Time of registration");
_("Purchase price");
_("from");
_("choose a date");
_("to");
_("choose a date");
_("from");
_("numbers only");
_("to");
_("numbers only");
_("Editing by");
_("Export");
_("Export");
_("Export CSV gives <br />jumps file with <br />a list of all<br /> users.");
_("Export Mailchimp sent <br />to all users on their<br /> email subscription<br /> form on your<br /> news rassilku.");
_("Orders history");
_("Order");
_("Time of the order");
_("Payment method");
_("Delivery method");
_("Cart");
_("Delivery price");
_("Total");
_("Status");
_("Order");
_("pcs");
_("Paid");
_("Paid");
_("Delete order");
_("Editing by");
_("Back");
_("Have been saved");
_("Save and go back");
_("User data");
_("ID");
_("Time of registration");
_("Purchase price");
_("Full name");
_("Telephone");
_("Address");
_("E-mail");
_("Role");
_("Additional data");
_("Content");
_("WishList");
_("Price");
_("Status");
_("Time of the order");
_("Orders");
_("Cart");
_("Total price");
_("Paid");
_("Order");
_("Purchased Product");
_("Pcs");
_("Yes");
_("No");

?>