<?php
/*
./templates/module_selector.tpl
./templates/cats_list.tpl
./templates/edit_item.tpl
./templates/main.tpl
./templates/create_menu.tpl
./templates/url_selector.tpl
./templates/pages_selector.tpl
./templates/category_selector.tpl
./templates/translate_item.tpl
./templates/edit_item_origin.tpl
./templates/_menulistitem.tpl
./templates/edit_menu.tpl
./templates/menu_list.tpl
./templates/create_item.tpl
./templates/cats.tpl
./templates/public/error.tpl*/

_("Options");
_("Type");
_("Module");
_("Name");
_("Title");
_("Function");
_("Parent");
_("No");
_("No");
_("First");
_("Image");
_("Select Image");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Yes");
_("No");
_("Create");
_("Cancel");
_("On page");
_("Pages list");
_("Parameters");
_("Parameters");
_("Parameters");
_("Method");
_("Example");
_("Type");
_("Show");
_("Edit link");
_("Go back");
_("Page");
_("Category");
_("Module");
_("Link");
_("On page");
_("Pages list");
_("Parameters");
_("Hide");
_("Create");
_("Cancel");
_("Error");
_("Choose category.");
_("Error");
_("Enter title.");
_("On page");
_("Pages list");
_("Parameters");
_("Parameters");
_("Parameters");
_("Method");
_("Example");
_("hide menu");
_("expand menu");
_("Edit menu item");
_("Translate menu item");
_("show");
_("Edit menu item");
_("Save and exit");
_("On page");
_("Pages list");
_("Options");
_("Choose an image ");
_("Options");
_("Choose an image ");
_("Parameters");
_("Function");
_("For example");
_("Choose an image ");
_("Choose an image ");
_("Attention");
_("Not found the required template file for menu");
_("Check file or change the settings menu");
_("Reinstall the module menu");
_("Select module");
_("Position after");
_("Open in the new window");
_("Edit menu item");
_("Go back");
_("Save");
_("Save and go back");
_("Page");
_("Categories");
_("Module");
_("Link");
_("Pages");
_("Categories");
_("Root");
_("Type");
_("Page");
_("ID");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Choose image ");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("Pages");
_("Choose a category");
_("Type");
_("Categories");
_("ID");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Choose an image ");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("Select module");
_("Type");
_("Module");
_("Name");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Choose an image ");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("URL");
_("Specify or select a link to the page");
_("Settings");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Choose an image ");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("Menu deleting");
_("Delete selected menu?");
_("Delete");
_("Cancel");
_("Menu");
_("Go back");
_("Create link");
_("Delete");
_("ID");
_("Name");
_("Link");
_("Create a menu");
_("Go back");
_("Create");
_("Save and go back");
_("Settings");
_("Name");
_("Title");
_("Description");
_("Template folder");
_("Open a menu, level");
_("Specify or select a link to the page");
_("Options");
_("URL");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Select an image");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("Create");
_("Cancel");
_("Save");
_("Pages");
_("Categories");
_("Root");
_("Type");
_("Page");
_("ID");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("Choose a category");
_("Options");
_("Type");
_("Categories");
_("ID");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Select an image");
_("Access level");
_("All");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("Menu item translate");
_("Go back");
_("Save");
_("Settings");
_("Edit menu item");
_("Go back");
_("Save");
_("Save and go back");
_("Page");
_("Categories");
_("Module");
_("Link");
_("Pages");
_("Categories");
_("Root");
_("Type");
_("Page");
_("ID");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Choose an image ");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("Pages");
_("Choose a category");
_("Type");
_("Categories");
_("ID");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Choose an image ");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("Select module");
_("Type");
_("Module");
_("Name");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Choose an image ");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("URL");
_("Specify or select a link to the page");
_("Settings");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Choose an image ");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("don't show");
_("Go back");
_("Save");
_("Edit a menu");
_("Name");
_("Title");
_("Description");
_("Template folder");
_("Open a menu, level");
_("Menu deleting");
_("Delete selected menu?");
_("Delete");
_("Cancel");
_("Menu list");
_("Create a menu");
_("Delete");
_("ID");
_("Denotation");
_("Name");
_("Description");
_("Created");
_("Editing");
_("Editing");
_("Edit menu item");
_("Go back");
_("Save");
_("Save and go back");
_("Page");
_("Categories");
_("Module");
_("Link");
_("Pages");
_("Categories");
_("Root");
_("Type");
_("Page");
_("ID");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("Pages");
_("Choose a category");
_("Type");
_("Categories");
_("ID");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("Select module");
_("Type");
_("Module");
_("Name");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");
_("URL");
_("Specify or select a link to the page");
_("Settings");
_("Title");
_("Parent");
_("No");
_("Position after");
_("No");
_("First");
_("Image");
_("Access level");
_("All");
_("Hide");
_("Yes");
_("No");
_("Open in the new window");
_("Yes");
_("No");

?>