<?php
/*
../../templates/newLevel/top_menu/level_0/container.tpl
../../templates/newLevel/new_level/one_product_item.tpl
../../templates/newLevel/comments/comments_api.tpl*/

_("s_buy");
_("s_message_o_report");
_("s_add_to_compare");
_("s_add_to_compare");
_("s_in_compare");
_("s_add_to_compare");
_("s_add_to_wish_list");
_("s_add_to_wish_list");
_("s_in_wish_list");
_("s_add_to_wish_list");
_("login_for_comments");
_("s_clients_comment");
_("s_plus");
_("s_cons");
_("s_comment_answer");
_("lang_comment_email");
_("s_you_raiting");
_("s_text_comment_one");
_("lang_captcha");
_("s_leave_comment");
_("lang_comment_author");
_("lang_comment_email");
_("s_leave_comment");

?>