<?php
namespace wishlist\classes;

require_once realpath(dirname(__FILE__) . '/../..') . '/enviroment.php';

doLogin();
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-27 at 13:08:15.
 */
class ParentWishlistTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ParentWishlist
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ParentWishlist;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers wishlist\classes\ParentWishlist::index
     * @todo   Implement testIndex().
     */
    public function testIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::all
     * @todo   Implement testAll().
     */
    public function testAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::show
     * @todo   Implement testShow().
     */
    public function testShow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::addReview
     * @todo   Implement testAddReview().
     */
    public function testAddReview()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::getMostViewedWishLists
     * @todo   Implement testGetMostViewedWishLists().
     */
    public function testGetMostViewedWishLists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::user
     * @todo   Implement testUser().
     */
    public function testUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::userUpdate
     * @todo   Implement testUserUpdate().
     */
    public function testUserUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::updateWL
     * @todo   Implement testUpdateWL().
     */
    public function testUpdateWL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::createWL
     * @todo   Implement testCreateWL().
     */
    public function testCreateWL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::createWishList
     * @todo   Implement testCreateWishList().
     */
    public function testCreateWishList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::deleteWL
     * @todo   Implement testDeleteWL().
     */
    public function testDeleteWL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::_addItem
     * @todo   Implement test_addItem().
     */
    public function test_addItem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::moveItem
     * @todo   Implement testMoveItem().
     */
    public function testMoveItem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::deleteItem
     * @todo   Implement testDeleteItem().
     */
    public function testDeleteItem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::getUserInfo
     * @todo   Implement testGetUserInfo().
     */
    public function testGetUserInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::renderUserWL
     * @todo   Implement testRenderUserWL().
     */
    public function testRenderUserWL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::renderUserWLEdit
     * @todo   Implement testRenderUserWLEdit().
     */
    public function testRenderUserWLEdit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::do_upload
     * @todo   Implement testDo_upload().
     */
    public function testDo_upload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::getMostPopularItems
     * @todo   Implement testGetMostPopularItems().
     */
    public function testGetMostPopularItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::getUserWishListItemsCount
     * @todo   Implement testGetUserWishListItemsCount().
     */
    public function testGetUserWishListItemsCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::deleteItemByIds
     * @todo   Implement testDeleteItemByIds().
     */
    public function testDeleteItemByIds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::deleteImage
     * @todo   Implement testDeleteImage().
     */
    public function testDeleteImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::renderPopup
     * @todo   Implement testRenderPopup().
     */
    public function testRenderPopup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::autoload
     * @todo   Implement testAutoload().
     */
    public function testAutoload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::adminAutoload
     * @todo   Implement testAdminAutoload().
     */
    public function testAdminAutoload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::_install
     * @todo   Implement test_install().
     */
    public function test_install()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wishlist\classes\ParentWishlist::_deinstall
     * @todo   Implement test_deinstall().
     */
    public function test_deinstall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
