<?php

namespace wishlist;

require_once realpath(dirname(__FILE__) . '/../../..') . '/enviroment.php';

doLogin();

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-01 at 17:13:31.
 */
class WishlistApiTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var WishlistApi
     */
    protected $object;
    protected $added;
    protected $operation_success;
    protected $updated_success;
    protected $no_views;
    protected $model;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new \wishlist\wishlistApi();
        $this->added = json_encode(array('answer' => 'success', 'data' => "<p>Добавлено</p>"));
        $this->operation_success = json_encode(array('answer' => 'success', 'data' => "<p>Операция успешна</p>"));
        $this->updated_success = json_encode(array('answer' => 'success', 'data' => array("<p>Обновлено</p>")));
        $this->no_views = json_encode(array('answer' => 'error', 'data' => array("<p>Нет просмотров</p>")));
        $this->model = new \Wishlist_model();

        $_POST = array(
            'wishlist' => 1,
            'wishListName' => "list",
            'listItem' => array(3),
            'user_id' => $GLOBALS['userId']
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers WishlistApi::all
     */
    public function test_deinstall() {
        $this->object->_deinstall();
    }

    public function test_install() {
        $this->object->_install();
    }

    /**
     * @covers WishlistApi::_addItem
     * @dataProvider addItem_provider
     */
    public function testaddItem($var_id) {
        $result = $this->object->addItem($var_id);
        $this->assertNotEmpty($result);
        $this->assertJsonStringEqualsJsonString($this->added, $result);
    }

    public function addItem_provider() {
        return array(
                array(1),
                array(2),
                array(3)
            );
    }

    /**
     * @covers WishlistApi::show
     */
    public function testShow() {

        //---------tested in BaseApiTest--------------//
    }

    /**
     * @covers WishlistApi::moveItem
     * @dataProvider moveItem_provider
     */
    public function testMoveItem($var_id, $wish_list_id) {
        $result = $this->object->moveItem($varId, $wish_list_id);
        $this->assertNotEmpty($result);
        $this->assertJsonStringEqualsJsonString($this->operation_success, $result);
    }

    public function moveItem_provider() {
        return array(
            array(1, 1),
            array(2, 2),
            array(3, 3)
        );
    }

    /**
     * @covers WishlistApi::updateWL
     * @dataProvider update_data_provider
     */
    public function testUpdateWL($list_id) {
        $_POST['WLID'] = $list_id;
        $_POST['comment'] = "test_wl_comment";
        $_POST['title'] = "test title";
        $_POST['access'] = 'public';

        $result = $this->object->updateWL();

        $this->assertNotEmpty($result);
        $this->assertJsonStringEqualsJsonString($this->updated_success, $result);
    }

    public function update_data_provider() {
        return array(
            array(1),
            array(2),
            array(3)
        );
    }

    public function testAll() {
        $result = $this->object->all();
        $result = json_decode($result);

        $this->assertObjectHasAttribute('lists', $result->data[0]);
        $this->assertObjectHasAttribute('user', $result->data[0]);
        $this->assertObjectHasAttribute('data', $result);
        $this->assertObjectHasAttribute('settings', $result);
        $this->assertObjectHasAttribute('answer', $result);

        $this->assertEquals('success', $result->answer);

        $this->assertNotEmpty($result->settings);
        $this->assertNotEmpty($result->data[0]->user);
        $this->assertNotEmpty($result->data[0]->lists);
    }


    /**
     * @covers WishlistApi::getMostViewedWishLists
     */
    public function testGetMostViewedWishLists() {
        //-----no views

        $result = $this->object->getMostViewedWishLists();
        $this->assertNotEmpty($result);
        $this->assertJsonStringEqualsJsonString($this->no_views, $result);

        //----prepare data to get most viewed lists

        $this->model->updateWishList(1, array('review_count' => 3));
        $this->model->updateWishList(2, array('review_count' => 2));

        $result = $this->object->getMostViewedWishLists();
        $result = json_decode($result);

        $this->assertObjectHasAttribute('answer', $result);
        $this->assertEquals('success', $result->answer);

        $this->assertObjectHasAttribute('data', $result);
        $this->assertGreaterThan(0, $result->data);
    }

    /**
     * @covers WishlistApi::user
     */
    public function testUser() {
        $result = $this->object->user($GLOBALS['userId'] );
        $result = json_decode($result);

        $this->assertObjectHasAttribute('answer', $result);
        $this->assertEquals('success', $result->answer);

        $this->assertObjectHasAttribute('data', $result);
        $this->assertGreaterThan(0, $result->data);

        $this->assertObjectHasAttribute('user', $result->data);
        $this->assertGreaterThan(0, $result->data->user);

        $this->assertObjectHasAttribute('id', $result->data->user);
        $this->assertNotEmpty($result->data->user->id);
    }

    /**
     * @covers WishlistApi::userUpdate
     */
    public function testUserUpdate() {
        $_POST['description'] = "test desc";
        $_POST['user_birthday'] = 112341234;
        $_POST['user_id'] = $GLOBALS['userId'] ;
        $_POST['user_name'] = "test_name";

        $result = $this->object->userUpdate();
        $result = json_decode($result);

        $this->assertNotEmpty($result);
        $this->assertObjectHasAttribute('answer', $result);
        $this->assertEquals('success', $result->answer);
    }

    /**
     * @covers WishlistApi::getMostPopularItems
     */
    public function testGetMostPopularItems() {
        $result = $this->object->getMostPopularItems();
        $result = json_decode($result);

        $this->assertNotEmpty($result);
        $this->assertObjectHasAttribute('answer', $result);
        $this->assertEquals('success', $result->answer);

        $this->assertObjectHasAttribute('data', $result);
        $this->assertGreaterThan(0, $result->data);
    }

    /**
     * @covers WishlistApi::createWishList
     */
    public function testCreateWishList() {
        $result = $this->object->createWishList();
        $result = json_decode($result);

        $this->assertNotEmpty($result);
        $this->assertObjectHasAttribute('answer', $result);
        $this->assertEquals('success', $result->answer);
    }

    /**
     * @covers WishlistApi::deleteWL
     */
    public function testDeleteWL() {
        $result = $this->object->deleteWL(2);
        $result = json_decode($result);

        $this->assertNotEmpty($result);
        $this->assertObjectHasAttribute('answer', $result);
        $this->assertEquals('success', $result->answer);
    }

    /**
     * @covers WishlistApi::deleteImage
     */
    public function testDeleteImage() {
        $_POST['image'] = 'test_image.jpg';
        write_file('../../../../uploads/mod_wishlist/test_image.jpg');
        $result = $this->object->deleteImage();
        $result = json_decode($result);

        $this->assertNotEmpty($result);
        $this->assertObjectHasAttribute('answer', $result);
        $this->assertEquals('success', $result->answer);
    }

    /**
     * @covers WishlistApi::renderWLButton
     * @dataProvider data_varId
     */
    public function testRenderWLButton($var_id) {
        $result = $this->object->renderWLButton($var_id);
        $result = json_decode($result);

        $this->assertNotEmpty($result);
        $this->assertObjectHasAttribute('value', $result);
        $this->assertObjectHasAttribute('varId', $result);
        $this->assertEquals($var_id, $result->varId);
        $this->assertGreaterThan(0, $result);
    }

    /**
     * @covers WishlistApi::renderPopup
     * @dataProvider data_varId
     */
    public function testRenderPopup($var_id) {
        $result = $this->object->renderPopup($var_id);
        $result = json_decode($result);

        $this->assertNotEmpty($result);
        $this->assertObjectHasAttribute('varId', $result);
        $this->assertObjectHasAttribute('wish_lists', $result);
        $this->assertEquals($var_id, $result->varId);
        $this->assertGreaterThan(0, $result->wish_lists);
    }

    public function data_varId() {
        return array(
            array(1),
            array(3)
        );
    }

    /**
     * @covers WishlistApi::editWL
     */
    public function testEditWL() {
        $result = $this->object->editWL(4, $GLOBALS['userId']);
        $result = json_decode($result);

        $this->assertNotEmpty($result);
        $this->assertObjectHasAttribute('answer', $result);
        $this->assertEquals('success', $result->answer);
        $this->assertObjectHasAttribute('wishlists', $result);
        $this->assertGreaterThan(0, $result->wishlists);
        
        //------When not existing wish list id
        $result = $this->object->editWL(10, $GLOBALS['userId']);
        $result = json_decode($result);
        
        $this->assertNotEmpty($result);
        $this->assertObjectHasAttribute('answer', $result);
        $this->assertEquals('error', $result->answer);
    }

    /**
     * @covers WishlistApi::do_upload
     */
    public function testDo_upload() {
        $result = $this->object->do_upload();
        $result = json_decode($result);
        
        $this->assertNotEmpty($result);
        $this->assertObjectHasAttribute('answer', $result);
        $this->assertEquals('error', $result->answer);
    }
    
    /**
     * @covers WishlistApi::deleteItem
     */
    public function testDeleteItem() {
        $result = $this->object->deleteItem(1, 1);
        $this->assertNotEmpty($result);
        $this->assertJsonStringEqualsJsonString($this->operation_success, $result);
    }

    /**
     * @covers WishlistApi::deleteItemsByIds
     */
    public function testDeleteItemsByIds() {
        $result = $this->object->deleteItemsByIds();
        
        $this->assertNotEmpty($result);
        $this->assertJsonStringEqualsJsonString($this->operation_success, $result);
    }

}