<?php

require_once realpath(dirname(__FILE__) . '/../../../..') . '/enviroment.php';
require_once APPPATH . 'modules/mod_seoexpert/models/seoexpert_model_products.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-10 at 12:53:17.
 */
class Seoexpert_model_productsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Seoexpert_model_products
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Seoexpert_model_products();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Seoexpert_model_products::getAllCategories
     * @todo   Implement testGetAllCategories().
     */
    public function testGetAllCategories() {
        $result = (boolean) $this->object->getAllCategories();
        $this->assertTrue($result);

        $result = (boolean) $this->object->getAllCategories('fdgdfg');
        $this->assertFalse($result);
    }

    /**
     * @covers Seoexpert_model_products::getProductCategory
     * @todo   Implement testGetProductCategory().
     */
    public function testGetProductCategory() {
        $result = (boolean) $this->object->getProductCategory(38);
        $this->assertTrue($result);

        $result = (boolean) $this->object->getProductCategory();
        $this->assertFalse($result);

        $result = (boolean) $this->object->getProductCategory('fdgdfg');
        $this->assertFalse($result);
    }

    /**
     * @covers Seoexpert_model_products::setProductCategory
     * @todo   Implement testSetProductCategory().
     */
    public function testSetProductCategory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Seoexpert_model_products::getCategoryByIdAndLocale
     * @todo   Implement testGetCategoryByIdAndLocale().
     */
    public function testGetCategoryByIdAndLocale() {
        $result = (boolean) $this->object->getCategoryByIdAndLocale(38);
        $this->assertTrue($result);

        $result = (boolean) $this->object->getCategoryByIdAndLocale(38, 'ru');
        $this->assertTrue($result);

        $result = (boolean) $this->object->getCategoryByIdAndLocale(38, 'asdfas');
        $this->assertFalse($result);

        $result = (boolean) $this->object->getCategoryByIdAndLocale();
        $this->assertFalse($result);

        $result = (boolean) $this->object->getCategoryByIdAndLocale('sdf');
        $this->assertFalse($result);
    }

    /**
     * @covers Seoexpert_model_products::getCategoriesArray
     * @todo   Implement testGetCategoriesArray().
     */
    public function testGetCategoriesArray() {

        $result = (boolean) $this->object->getCategoriesArray();
        $this->assertTrue($result);
    }

    /**
     * @covers Seoexpert_model_products::getCategoryNameAndId
     * @todo   Implement testGetCategoryNameAndId().
     */
    public function testGetCategoryNameAndId() {
        $result = (boolean) $this->object->getCategoryNameAndId();
        $this->assertFalse($result);
        
        $result = (boolean) $this->object->getCategoryNameAndId('sdd');
        $this->assertFalse($result);
        
        $result = (boolean) $this->object->getCategoryNameAndId(38);
        $this->assertTrue($result);
    }

}
