<?php

/**
 * @TODO: Решить со свойствами
 */
$setting['migration'] = [
                         'productTemplate'                        => [
                                                                      '%ID%'            => '{{product.id}}',
                                                                      '%name%'          => '{{product.name}}',
                                                                      '%category%'      => '{{category.name}}',
                                                                      '%brand%'         => '{{product.brand}}',
                                                                      '%price%'         => '{{product.price}}',
                                                                      '%CS%'            => '{{CS}}',
//                '%p_xxxx%'        => '{{property.id}}',
                                                                      '%name[t]%'       => '{{product.name|translit}}',
                                                                      '%name[1]%'       => '{{product.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{product.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{product.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{product.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{product.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{product.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{product.name|morphy(1..6)|translit}}',
                                                                     ],
                         'productTemplateDesc'                    => [
                                                                      '%ID%'            => '{{product.id}}',
                                                                      '%name%'          => '{{product.name}}',
                                                                      '%desc%'          => '{{product.desc}}',
                                                                      '%category%'      => '{{category.name}}',
                                                                      '%brand%'         => '{{product.brand}}',
                                                                      '%price%'         => '{{product.price}}',
                                                                      '%CS%'            => '{{CS}}',
                         //                '%p_xxxx%'        => '{{property.id}}',
                                                                      '%name[t]%'       => '{{product.name|translit}}',
                                                                      '%name[1]%'       => '{{product.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{product.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{product.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{product.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{product.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{product.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{product.name|morphy(1..6)|translit}}',
                                                                     ],
                         'productTemplateDescCount'               => [
                                                                      '%ID%'            => '{{product.id}}',
                                                                      '%name%'          => '{{product.name}}',
                                                                      '%desc%'          => '{{product.description}}',
                                                                      '%category%'      => '{{category.name}}',
                                                                      '%brand%'         => '{{product.brand}}',
                                                                      '%price%'         => '{{product.price}}',
                                                                      '%CS%'            => '{{CS}}',
                         //'%p_xxxx%'        => '{{property.id}}',
                                                                      '%name[t]%'       => '{{product.name|translit}}',
                                                                      '%name[1]%'       => '{{product.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{product.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{product.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{product.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{product.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{product.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{product.name|morphy(1..6)|translit}}',
                                                                     ],
                         'productTemplateKey'                     => [
                                                                      '%name%'     => '{{product.name}}',
                                                                      '%category%' => '{{category.name}}',
                                                                      '%brand%'    => '{{product.brand}}',
                                                                      '%CS%'       => '{{CS}}',
                         //'%p_xxxx%'        => '{{property.id}}',
                                                                      '%name[t]%'  => '{{product.name|translit}}',
                                                                     ],
                         'categoryTemplate'                       => [
                                                                      '%ID%'            => '{{category.id}}',
                                                                      '%name%'          => '{{category.name}}',
                                                                      '%desc%'          => '{{category.description}}',
                                                                      '%H1%'            => '{{category.title}}',
                                                                      '%brands%'        => '{{category.brand}}',
                                                                      '%pagenumber%'    => '{{page_number}}',
                                                                      '%maxPrice%'      => '{{maxPrice}}',
                                                                      '%minPrice%'      => '{{minPrice}}',
                                                                      '%name[t]%'       => '{{category.name|translit}}',
                                                                      '%name[1]%'       => '{{category.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{category.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{category.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{category.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{category.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{category.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{category.name|morphy(1..6)|translit}}',
                                                                     ],
                         'categoryTemplateDesc'                   => [
                                                                      '%ID%'            => '{{category.id}}',
                                                                      '%name%'          => '{{category.name}}',
                                                                      '%desc%'          => '{{category.description}}',
                                                                      '%H1%'            => '{{category.title}}',
                                                                      '%brands%'        => '{{category.brand}}',
                                                                      '%pagenumber%'    => '{{page_number}}',
                                                                      '%maxPrice%'      => '{{maxPrice}}',
                                                                      '%minPrice%'      => '{{minPrice}}',
                                                                      '%name[t]%'       => '{{category.name|translit}}',
                                                                      '%name[1]%'       => '{{category.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{category.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{category.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{category.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{category.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{category.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{category.name|morphy(1..6)|translit}}',
                                                                     ],
                         'categoryTemplateKey'                    => [
                                                                      '%ID%'         => '{{category.id}}',
                                                                      '%name%'       => '{{category.name}}',
                                                                      '%desc%'       => '{{category.description}}',
                                                                      '%H1%'         => '{{category.title}}',
                                                                      '%brands%'     => '{{category.brand}}',
                                                                      '%pagenumber%' => '{{page_number}}',
                                                                     ],
                         'categoryTemplatePaginationTemplate'     => ['%pagenumber%' => '{{page_number}}'],
                         'subcategoryTemplate'                    => [
                                                                      '%ID%'            => '{{category.id}}',
                                                                      '%name%'          => '{{category.name}}',
                                                                      '%desc%'          => '{{category.description}}',
                                                                      '%H1%'            => '{{category.title}}',
                                                                      '%brands%'        => '{{category.brand}}',
                                                                      '%pagenumber%'    => '{{page_number}}',
                                                                      '%maxPrice%'      => '{{maxPrice}}',
                                                                      '%minPrice%'      => '{{minPrice}}',
                                                                      '%name[t]%'       => '{{category.name|translit}}',
                                                                      '%name[1]%'       => '{{category.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{category.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{category.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{category.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{category.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{category.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{category.name|morphy(1..6)|translit}}',
                                                                     ],
                         'subcategoryTemplateDesc'                => [
                                                                      '%ID%'            => '{{category.id}}',
                                                                      '%name%'          => '{{category.name}}',
                                                                      '%desc%'          => '{{category.description}}',
                                                                      '%H1%'            => '{{category.title}}',
                                                                      '%brands%'        => '{{category.brand}}',
                                                                      '%pagenumber%'    => '{{page_number}}',
                                                                      '%maxPrice%'      => '{{maxPrice}}',
                                                                      '%minPrice%'      => '{{minPrice}}',
                                                                      '%name[t]%'       => '{{category.name|translit}}',
                                                                      '%name[1]%'       => '{{category.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{category.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{category.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{category.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{category.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{category.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{category.name|morphy(1..6)|translit}}',
                                                                     ],
                         'subcategoryTemplateKey'                 => [
                                                                      '%ID%'         => '{{category.id}}',
                                                                      '%name%'       => '{{category.name}}',
                                                                      '%desc%'       => '{{category.description}}',
                                                                      '%H1%'         => '{{category.title}}',
                                                                      '%brands%'     => '{{category.brand}}',
                                                                      '%pagenumber%' => '{{page_number}}',
                                                                     ],
                         'subcategoryTemplatePaginationTemplate'  => ['%pagenumber%' => '{{page_number}}'],
                         'brandTemplate'                          => [
                                                                      '%ID%'         => '{{brand.id}}',
                                                                      '%name%'       => '{{brand.name}}',
                                                                      '%desc%'       => '{{brand.description}}',
                                                                      '%pagenumber%' => '{{page_number}}',
                                                                      '%name[t]%'    => '{{brand.name|translit}}',
                                                                     ],
                         'brandTemplateDesc'                      => [
                                                                      '%ID%'         => '{{brand.id}}',
                                                                      '%name%'       => '{{brand.name}}',
                                                                      '%desc%'       => '{{brand.description}}',
                                                                      '%pagenumber%' => '{{page_number}}',
                                                                      '%name[t]%'    => '{{brand.name|translit}}',
                                                                     ],
                         'brandPaginationTemplate'                => ['%number%' => '{{page_number}}'],
                         'brandTemplateKey'                       => [
                                                                      '%name%'       => '{{brand.name}}',
                                                                      '%pagenumber%' => '{{page_number}}',
                                                                     ],
                         'pageTemplateTitle'                      => [
                                                                      '%name%'          => '{{page.name}}',
                                                                      '%category%'      => '{{category.name}}',
                                                                      '%name[t]%'       => '{{page.name|translit}}',
                                                                      '%name[1]%'       => '{{page.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{page.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{page.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{page.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{page.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{page.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{page.name|morphy(1..6)|translit}}',
                                                                     ],
                         'pageTemplateDesc'                       => [
                                                                      '%name%'          => '{{page.name}}',
                                                                      '%desc%'          => '{{page.description}}',
                                                                      '%category%'      => '{{category.name}}',
                                                                      '%name[t]%'       => '{{page.name|translit}}',
                                                                      '%name[1]%'       => '{{page.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{page.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{page.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{page.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{page.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{page.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{page.name|morphy(1..6)|translit}}',
                                                                     ],
                         'pageTemplateKey'                        => [
                                                                      '%name%'          => '{{page.name}}',
                                                                      '%category%'      => '{{category.name}}',
                                                                      '%name[t]%'       => '{{page.name|translit}}',
                                                                      '%name[1]%'       => '{{page.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{page.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{page.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{page.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{page.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{page.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{page.name|morphy(1..6)|translit}}',
                                                                     ],
                         'pageCategoryTemplateTitle'              => [
                                                                      '%name%'          => '{{category.name}}',
                                                                      '%pagenumber%'    => '{{page_number}}',
                                                                      '%name[t]%'       => '{{category.name|translit}}',
                                                                      '%name[1]%'       => '{{category.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{category.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{category.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{category.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{category.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{category.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{category.name|morphy(1..6)|translit}}',
                                                                     ],
                         'pageCategoryTemplateDesc'               => [
                                                                      '%name%'          => '{{category.name}}',
                                                                      '%pagenumber%'    => '{{page_number}}',
                                                                      '%desc%'          => '{{category.description}}',
                                                                      '%name[t]%'       => '{{category.name|translit}}',
                                                                      '%name[1]%'       => '{{category.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{category.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{category.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{category.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{category.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{category.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{category.name|morphy(1..6)|translit}}',
                                                                     ],
                         'pageCategoryTemplateKey'                => [
                                                                      '%name%'          => '{{category.name}}',
                                                                      '%pagenumber%'    => '{{page_number}}',
                                                                      '%name[t]%'       => '{{category.name|translit}}',
                                                                      '%name[1]%'       => '{{category.name|morphy(1)}}',
                                                                      '%name[2]%'       => '{{category.name|morphy(2)}}',
                                                                      '%name[3]%'       => '{{category.name|morphy(3)}}',
                                                                      '%name[4]%'       => '{{category.name|morphy(4)}}',
                                                                      '%name[5]%'       => '{{category.name|morphy(5)}}',
                                                                      '%name[6]%'       => '{{category.name|morphy(6)}}',
                                                                      '%name[1..6][t]%' => '{{category.name|morphy(1..6)|translit}}',
                                                                     ],
                         'pageCategoryTemplatePaginationTemplate' => ['%number%' => '{{page_number}}'],
                         'galleryCategoryTemplate'                => ['%name%' => '{{category.name}}'],
                         'galleryCategoryTemplateDesc'            => [
                                                                      '%name%' => '{{category.name}}',
                                                                      '%desc%' => '{{category.description}}',
                                                                     ],
                         'galleryCategoryTemplateKey'             => ['%name%' => '{{category.name}}'],
                         'galleryAlbumTemplate'                   => [
                                                                      '%name%'     => '{{album.name}}',
                                                                      '%category%' => '{{category.name}}',
                                                                     ],
                         'galleryAlbumTemplateDesc'               => [
                                                                      '%name%'     => '{{album.name}}',
                                                                      '%category%' => '{{category.name}}',
                                                                      '%desc%'     => '{{album.description}}',
                                                                     ],
                         'galleryAlbumTemplateKey'                => [
                                                                      '%name%'     => '{{album.name}}',
                                                                      '%category%' => '{{category.name}}',
                                                                     ],

                        ];