<?php

$I = new AcceptanceTester($scenario);
initTest::login($I);
$I->amOnPage('/');
$I->waitForText('Заказать звонок');
$I->click('.isDrop');
$I->waitForElement('.btn-form>button');
$I->fillField('.//*[@id="data-callback"]/label[1]/span[2]/input', 'qwert12345!@#$%^&*()_+|}{:?></.,;[]`йцуке');
$I->fillField('.//*[@id="data-callback"]/label[2]/span[2]/input', 'qwert12345!@#$%^&*()_+|}{:?></.,;[]`йцуке');
$I->fillField('.//*[@id="data-callback"]/label[3]/span[2]/textarea', 'qwert12345!@#$%^&*()_+|}{:?></.,;[]`йцуке');
$I->click('.btn-form>button');
$I->waitForElement('.//*[@id="data-callback"]/label[2]/span[2]/label');
$I->see('Поле Телефон должно содержать только цифры.', './/*[@id="data-callback"]/label[2]/span[2]/label');
$I->fillField('.//*[@id="data-callback"]/label[2]/span[2]/input', 'qwert1');
$I->click('.btn-form>button');
$I->waitForElement('.//*[@id="data-callback"]/label[2]/span[2]/label');
$I->see('Поле Телефон должно содержать только цифры.', './/*[@id="data-callback"]/label[2]/span[2]/label');
$I->fillField('.//*[@id="data-callback"]/label[2]/span[2]/input', '2345!@#$%^&*()_+|}{');
$I->click('.btn-form>button');
$I->waitForElement('.//*[@id="data-callback"]/label[2]/span[2]/label');
$I->see('Поле Телефон должно содержать только цифры.', './/*[@id="data-callback"]/label[2]/span[2]/label');
$I->fillField('.//*[@id="data-callback"]/label[2]/span[2]/input', '65йцуке');
$I->click('.btn-form>button');
$I->waitForElement('.//*[@id="data-callback"]/label[2]/span[2]/label');
$I->see('Поле Телефон должно содержать только цифры.', './/*[@id="data-callback"]/label[2]/span[2]/label');
$I->fillField('.//*[@id="data-callback"]/label[2]/span[2]/input', '12345');
$I->click('.btn-form>button');
$I->waitForElement('div.text-el>h1');
$povid=$I->grabTextFrom('div.text-el>h1');
$pov=$I->grabTextFrom('div.text-el>div');
$I->waitForElementNotVisible('.//*[@id="ordercall"]');
$I->amOnPage('/admin');
$I->click('html/body/div[1]/div[3]/div/nav/ul/li[8]/a');
$I->click('html/body/div[1]/div[3]/div/nav/ul/li[8]/ul/li[1]/a');
$I->waitForText('Настройки магазина');
$I->click('.//*[@id="mainContent"]/section/div[2]/div[1]/ul/li[4]/a');
$I->waitForElement('//*[@id="notif"]/table/thead/tr/th');
//$povid1=$I->grabTextFrom(".//*[@id='notif']/table/tbody/tr/td/div/div[2]/div/div/div[2]/textarea");
//$I->comment("$povid1");
//$pov1=$I->grabTextFrom('.//*[@id="notif"]/table/tbody/tr/td/div/div[2]/div/div/div[2]/textarea/div');
//$I->assertEquals($povid, $povid1);
//$I->assertEquals($pov, $pov1);
$text=$I->executeJS('window.frames[1].document.body.getElementsByTagName("h1")');
//$text = $I->grabTextFrom("window.frames[1].document.body.getElementsByTagName('h1').value");
$I->comment("$text");
$I->assertEquals($povid, $text);