<?php

$I = new AcceptanceTester($scenario);
initTest::login($I);
$I->amOnPage('/admin/components/run/shop/callbacks');
$I->click('.//*[@id="callbacks_all"]/table/tbody/tr[1]/td[3]/a');
$I->waitForElement('.//*[@id="editCallbackForm"]/div[2]/label');
$I->fillField(CallbacksPage::$UserNameEdit, 'qwert12345!@#$%^&*()_+|}{:?></.,;[]`йцуке');
$I->fillField(CallbacksPage::$TelephoneEdit, 'qwert12345!@#$%^&*()_+|}{:?></.,;[]`йцуке');
$I->fillField(CallbacksPage::$CommentEdit, 'qwert12345!@#$%^&*()_+|}{:?></.,;[]`йцуке');
$I->click(CallbacksPage::$SaveButton);
$I->waitForElementVisible('.alert.in.fade.alert-success');
$I->see('Поле Телефон должно содержать только цифры.');
$I->waitForElementNotVisible('.alert.in.fade.alert-success');
$I->fillField(CallbacksPage::$TelephoneEdit, 'qwert1');
$I->click(CallbacksPage::$SaveButton);
$I->waitForElementVisible('.alert.in.fade.alert-success');
$I->see('Поле Телефон должно содержать только цифры.');
$I->waitForElementNotVisible('.alert.in.fade.alert-success');
$I->fillField(CallbacksPage::$TelephoneEdit, '2345!@#$%^&*()_+|}{');
$I->click(CallbacksPage::$SaveButton);
$I->waitForElementVisible('.alert.in.fade.alert-success');
$I->see('Поле Телефон должно содержать только цифры.');
$I->waitForElementNotVisible('.alert.in.fade.alert-success');
$I->fillField(CallbacksPage::$TelephoneEdit, '65йцуке');
$I->click(CallbacksPage::$SaveButton);
$I->waitForElementVisible('.alert.in.fade.alert-success');
$I->see('Поле Телефон должно содержать только цифры.');
$I->waitForElementNotVisible('.alert.in.fade.alert-success');
$I->fillField(CallbacksPage::$TelephoneEdit, '12345');
$I->click(CallbacksPage::$SaveButton);
$I->waitForElementVisible('.alert.in.fade.alert-success');
$I->see('Изменения сохранены');
$I->waitForElementNotVisible('.alert.in.fade.alert-success');
$I->seeInField(CallbacksPage::$UserNameEdit, 'qwert12345!@#$%^&*()_+|}{:?></.,;[]`йцуке');
$I->seeInField(CallbacksPage::$TelephoneEdit, '12345');
$I->seeInField(CallbacksPage::$CommentEdit, 'qwert12345!@#$%^&*()_+|}{:?></.,;[]`йцуке');
$I->click(CallbacksPage::$GoBackButton);
$I->waitForText('Список обратных звонков');
$I->see('qwert12345!@#$%^&*()_+|}{:?></.,;[]`йцуке', './/*[@id="callbacks_all"]/table/tbody/tr[1]/td[3]/a');
$I->see('12345', './/*[@id="callbacks_all"]/table/tbody/tr[1]/td[4]');

