#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
 
# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
	oIFS=$IFS
	IFS='
	'
	SFILES="$1"
	IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "================="
echo "Checking PHP Lint..."
echo "================="
for FILE in $SFILES
do
	php -l -d display_errors=0 $PROJECT/$FILE
	if [ $? != 0 ]
	then
		echo "Fix the error before commit."
		exit 1
	fi
	FILES="$FILES $PROJECT/$FILE"
done
 
if [ "$FILES" != "" ]
then
	echo "================="
	echo "Running Code Sniffer..."
	echo "================="
	
	./application/third_party/bin/phpcbf --standard=$PROJECT/hooks/ImageCMS $FILES 
	./application/third_party/bin/phpcs --standard=$PROJECT/hooks/ImageCMS $FILES 
	if [ $? != 0 ]
	then
		EXIT=1
	fi
fi

echo "================="
echo "Checking PHPMD..."
echo "================="
for FILE in $SFILES
do
	./application/third_party/bin/phpmd $PROJECT/$FILE text $PROJECT/hooks/phpmd.xml --exclude=propel/generated-classes/*
	if [ $? != 0 ]
	then
		EXIT=1
	fi
done

if [ "$EXIT" = 1 ]
then
 echo '          _____                    _____                    _____                   _______                   _____          
         /\    \                  /\    \                  /\    \                 /::\    \                 /\    \         
        /::\    \                /::\    \                /::\    \               /::::\    \               /::\    \        
       /::::\    \              /::::\    \              /::::\    \             /::::::\    \             /::::\    \       
      /::::::\    \            /::::::\    \            /::::::\    \           /::::::::\    \           /::::::\    \      
     /:::/\:::\    \          /:::/\:::\    \          /:::/\:::\    \         /:::/~~\:::\    \         /:::/\:::\    \     
    /:::/__\:::\    \        /:::/__\:::\    \        /:::/__\:::\    \       /:::/    \:::\    \       /:::/__\:::\    \    
   /::::\   \:::\    \      /::::\   \:::\    \      /::::\   \:::\    \     /:::/    / \:::\    \     /::::\   \:::\    \   
  /::::::\   \:::\    \    /::::::\   \:::\    \    /::::::\   \:::\    \   /:::/____/   \:::\____\   /::::::\   \:::\    \  
 /:::/\:::\   \:::\    \  /:::/\:::\   \:::\____\  /:::/\:::\   \:::\____\ |:::|    |     |:::|    | /:::/\:::\   \:::\____\ 
/:::/__\:::\   \:::\____\/:::/  \:::\   \:::|    |/:::/  \:::\   \:::|    ||:::|____|     |:::|    |/:::/  \:::\   \:::|    |
\:::\   \:::\   \::/    /\::/   |::::\  /:::|____|\::/   |::::\  /:::|____| \:::\    \   /:::/    / \::/   |::::\  /:::|____|
 \:::\   \:::\   \/____/  \/____|:::::\/:::/    /  \/____|:::::\/:::/    /   \:::\    \ /:::/    /   \/____|:::::\/:::/    / 
  \:::\   \:::\    \            |:::::::::/    /         |:::::::::/    /     \:::\    /:::/    /          |:::::::::/    /  
   \:::\   \:::\____\           |::|\::::/    /          |::|\::::/    /       \:::\__/:::/    /           |::|\::::/    /   
    \:::\   \::/    /           |::| \::/____/           |::| \::/____/         \::::::::/    /            |::| \::/____/    
     \:::\   \/____/            |::|  ~|                 |::|  ~|                \::::::/    /             |::|  ~|          
      \:::\    \                |::|   |                 |::|   |                 \::::/    /              |::|   |          
       \:::\____\               \::|   |                 \::|   |                  \::/____/               \::|   |          
        \::/    /                \:|   |                  \:|   |                   ~~                      \:|   |          
         \/____/                  \|___|                   \|___|                                            \|___|          
                                                                                                                             '
	exit 1
fi