<pre>string(26) "Delete selected module(s)?"
</pre><pre>string(26) "Delete selected widget(s)?"
</pre><pre>string(17) "Modules additions"
</pre><pre>string(51) "The key to your account <br />on the mail Mailchimp"
</pre><pre>string(48) "The key to your list of <br />news for MailChimp"
</pre><pre>string(114) "Export Mailchimp sent <br />to all users on their<br /> email subscription<br /> form on your<br /> news rassilku."
</pre><pre>string(59) "No configuration key or<br /> key account list on Mailchimp"
</pre><pre>string(9) "Edit page"
</pre><pre>string(9) "Show page"
</pre><pre>string(2) "No"
</pre><pre>string(12) "Autocomplete"
</pre><pre>string(18) "Autocomplete words"
</pre><pre>string(11) "choose date"
</pre><pre>string(6) "Cancel"
</pre><pre>string(6) "Create"
</pre><pre>string(7) "Preview"
</pre><pre>string(4) "site"
</pre><pre>string(6) "Orders"
</pre><pre>string(11) "Manage shop"
</pre><pre>string(11) "All modules"
</pre><pre>string(11) "Manage site"
</pre><pre>string(9) "Interface"
</pre><pre>string(18) "Help us get better"
</pre><pre>string(15) "report an error"
</pre><pre>string(13) "Documentation"
</pre><pre>string(9) "Your Name"
</pre><pre>string(10) "Your Email"
</pre><pre>string(11) "Your remark"
</pre><pre>string(6) "Return"
</pre><pre>string(16) "Full description"
</pre><pre>string(6) "Parent"
</pre><pre>string(25) "Your search did not found"
</pre><pre>string(7) "Confirm"
</pre><pre>string(12) "Delete pages"
</pre><pre>string(22) "Delete selected pages?"
</pre><pre>string(13) "Articles list"
</pre><pre>string(6) "Filter"
</pre><pre>string(11) "Create copy"
</pre><pre>string(4) "Move"
</pre><pre>string(6) "Delete"
</pre><pre>string(11) "Create page"
</pre><pre>string(14) "All categories"
</pre><pre>string(5) "Title"
</pre><pre>string(3) "Url"
</pre><pre>string(8) "Category"
</pre><pre>string(13) "Creation date"
</pre><pre>string(6) "Status"
</pre><pre>string(11) "Digits only"
</pre><pre>string(16) "Without category"
</pre><pre>string(15) "Update settings"
</pre><pre>string(4) "Back"
</pre><pre>string(4) "Save"
</pre><pre>string(8) "Settings"
</pre><pre>string(17) "Your updation key"
</pre><pre>string(17) "Create role group"
</pre><pre>string(9) "Privilege"
</pre><pre>string(22) "Delete selected groups"
</pre><pre>string(12) "Delete group"
</pre><pre>string(5) "Clean"
</pre><pre>string(15) "Operation panel"
</pre><pre>string(31) "Users with such Email not found"
</pre><pre>string(13) "Security code"
</pre><pre>string(15) "Update the code"
</pre><pre>string(8) "Remember"
</pre><pre>string(21) "Forgot your password?"
</pre><pre>string(6) "Log in"
</pre><pre>string(7) "Russian"
</pre><pre>string(7) "English"
</pre><pre>string(8) "Language"
</pre><pre>string(16) "roll up category"
</pre><pre>string(15) "expand category"
</pre><pre>string(13) "edit category"
</pre><pre>string(10) "go to site"
</pre><pre>string(27) "Save and create a new group"
</pre><pre>string(13) "Save and edit"
</pre><pre>string(5) "Group"
</pre><pre>string(15) "Create new page"
</pre><pre>string(4) "back"
</pre><pre>string(15) "Parent category"
</pre><pre>string(18) "Check mail sending"
</pre><pre>string(5) "Check"
</pre><pre>string(7) "Warning"
</pre><pre>string(27) "Not enough rights to access"
</pre><pre>string(13) "Widget delete"
</pre><pre>string(12) "Widgets list"
</pre><pre>string(15) "Create a widget"
</pre><pre>string(2) "ID"
</pre><pre>string(4) "Name"
</pre><pre>string(4) "Type"
</pre><pre>string(11) "Description"
</pre><pre>string(7) "Editing"
</pre><pre>string(6) "Module"
</pre><pre>string(4) "HTML"
</pre><pre>string(18) "No widgets created"
</pre><pre>string(17) "Roles groups list"
</pre><pre>string(4) "List"
</pre><pre>string(6) "Empty."
</pre><pre>string(13) "Remove roles?"
</pre><pre>string(5) "Cache"
</pre><pre>string(12) "Delete cache"
</pre><pre>string(18) "Total file caching"
</pre><pre>string(14) "Clear outdated"
</pre><pre>string(9) "Clear all"
</pre><pre>string(15) "Privileges list"
</pre><pre>string(16) "Create privilege"
</pre><pre>string(11) "Role remove"
</pre><pre>string(22) "Remove selected roles?"
</pre><pre>string(27) "Delete the file to continue"
</pre><pre>string(6) "E-mail"
</pre><pre>string(8) "Password"
</pre><pre>string(18) "Roles group create"
</pre><pre>string(10) "Properties"
</pre><pre>string(17) "Add a subcategory"
</pre><pre>string(14) "Add an article"
</pre><pre>string(35) "Double click to show all categories"
</pre><pre>string(20) "Change category data"
</pre><pre>string(6) "Author"
</pre><pre>string(7) "Version"
</pre><pre>string(7) "Install"
</pre><pre>string(8) "Download"
</pre><pre>string(23) "FTP connection settings"
</pre><pre>string(8) "Hostname"
</pre><pre>string(4) "Port"
</pre><pre>string(5) "login"
</pre><pre>string(26) "Path to the root directory"
</pre><pre>string(11) "For example"
</pre><pre>string(4) "Next"
</pre><pre>string(16) "Save and go back"
</pre><pre>string(7) "Content"
</pre><pre>string(17) "Additional fields"
</pre><pre>string(10) "Categories"
</pre><pre>string(17) "Create a category"
</pre><pre>string(20) "Preliminary contents"
</pre><pre>string(13) "Full contents"
</pre><pre>string(3) "URL"
</pre><pre>string(21) "Only Latin characters"
</pre><pre>string(4) "Tags"
</pre><pre>string(10) "Meta Title"
</pre><pre>string(16) "Meta Description"
</pre><pre>string(13) "Meta Keywords"
</pre><pre>string(13) "Main template"
</pre><pre>string(10) "by default"
</pre><pre>string(13) "Page Template"
</pre><pre>string(18) "Comment permission"
</pre><pre>string(18) "Publication status"
</pre><pre>string(9) "Published"
</pre><pre>string(17) "Waiting approval "
</pre><pre>string(11) "Unpublished"
</pre><pre>string(25) "Time and date of creation"
</pre><pre>string(28) "Time and date of publication"
</pre><pre>string(6) "Access"
</pre><pre>string(3) "All"
</pre><pre>string(15) "Create and exit"
</pre><pre>string(9) "Meta tags"
</pre><pre>string(7) "AutoFit"
</pre><pre>string(11) "Field group"
</pre><pre>string(35) "Select a field group for a category"
</pre><pre>string(23) "Apply for subcategories"
</pre><pre>string(18) "Pages fields group"
</pre><pre>string(99) "Select a field group to be displayed/ viewed in the created category of the group or group category"
</pre><pre>string(5) "Image"
</pre><pre>string(16) "Choose an image "
</pre><pre>string(8) "Position"
</pre><pre>string(9) "View page"
</pre><pre>string(7) "Sort by"
</pre><pre>string(7) "by date"
</pre><pre>string(38) "By alphabet or in the alphabetic order"
</pre><pre>string(11) "By position"
</pre><pre>string(19) "In descending order"
</pre><pre>string(18) "In ascending order"
</pre><pre>string(13) "Posts on page"
</pre><pre>string(25) "Comment pages by default "
</pre><pre>string(33) "Display pages of other categories"
</pre><pre>string(33) "Main category template by default"
</pre><pre>string(17) "Category template"
</pre><pre>string(13) "Page template"
</pre><pre>string(29) "Page view template by default"
</pre><pre>string(10) "Privileges"
</pre><pre>string(18) "System information"
</pre><pre>string(27) "Level of server utilisation"
</pre><pre>string(6) "Server"
</pre><pre>string(16) "Operating system"
</pre><pre>string(9) "Data base"
</pre><pre>string(6) "Period"
</pre><pre>string(4) "Size"
</pre><pre>string(16) "Write permission"
</pre><pre>string(19) "Module deinstalling"
</pre><pre>string(15) "Delete modules?"
</pre><pre>string(7) "Modules"
</pre><pre>string(15) "Install modules"
</pre><pre>string(13) "Auto loading "
</pre><pre>string(10) "URL access"
</pre><pre>string(12) "Show in menu"
</pre><pre>string(5) "Users"
</pre><pre>string(9) "switch on"
</pre><pre>string(10) "switch off"
</pre><pre>string(30) "Modules has not been installed"
</pre><pre>string(36) "There is not any module for install!"
</pre><pre>string(4) "Main"
</pre><pre>string(10) "All orders"
</pre><pre>string(12) "Order status"
</pre><pre>string(9) "Callbacks"
</pre><pre>string(8) "Callback"
</pre><pre>string(17) "Callback statuses"
</pre><pre>string(15) "Callback themes"
</pre><pre>string(25) "Reports of the appearance"
</pre><pre>string(26) "Statuses of the appearance"
</pre><pre>string(6) "Others"
</pre><pre>string(8) "Comments"
</pre><pre>string(16) "Products catalog"
</pre><pre>string(8) "Products"
</pre><pre>string(19) "Products properties"
</pre><pre>string(13) "Products sets"
</pre><pre>string(23) "Products without images"
</pre><pre>string(10) "Users list"
</pre><pre>string(27) "Management of access rights"
</pre><pre>string(10) "Components"
</pre><pre>string(6) "Brands"
</pre><pre>string(9) "Warehouse"
</pre><pre>string(7) "Banners"
</pre><pre>string(21) "Progressive discounts"
</pre><pre>string(17) "Gift Certificates"
</pre><pre>string(15) "Global settings"
</pre><pre>string(8) "Currency"
</pre><pre>string(15) "Delivery method"
</pre><pre>string(11) "Payd method"
</pre><pre>string(10) "Automation"
</pre><pre>string(15) "Administer site"
</pre><pre>string(20) "Category translation"
</pre><pre>string(14) "Search results"
</pre><pre>string(14) "Widget editing"
</pre><pre>string(13) "Save and exit"
</pre><pre>string(9) "HTML code"
</pre><pre>string(7) "Forward"
</pre><pre>string(6) "Update"
</pre><pre>string(9) "Main page"
</pre><pre>string(33) "Sorry but you have an old browser"
</pre><pre>string(36) "Update or download new browsers here"
</pre><pre>string(10) "Importance"
</pre><pre>string(4) "Shop"
</pre><pre>string(4) "Base"
</pre><pre>string(8) "Updation"
</pre><pre>string(13) "Create Backup"
</pre><pre>string(5) "Error"
</pre><pre>string(7) "Restore"
</pre><pre>string(26) "Files that will be changed"
</pre><pre>string(9) "File path"
</pre><pre>string(11) "Control sum"
</pre><pre>string(15) "Date of changes"
</pre><pre>string(15) "Empty file list"
</pre><pre>string(8) "Deleting"
</pre><pre>string(18) "No recovery files."
</pre><pre>string(11) "Tools panel"
</pre><pre>string(13) "Uncategorized"
</pre><pre>string(23) "No recently added pages"
</pre><pre>string(25) "No recently updated pages"
</pre><pre>string(20) "Check version update"
</pre><pre>string(22) "Latest/recent comments"
</pre><pre>string(13) "ImageCMS news"
</pre><pre>string(15) "Delete language"
</pre><pre>string(26) "Delete selected languages?"
</pre><pre>string(54) "Attention! All pages in this language will be deleted!"
</pre><pre>string(9) "Languages"
</pre><pre>string(15) "Create language"
</pre><pre>string(41) "Select the module type to the table below"
</pre><pre>string(16) "Module installed"
</pre><pre>string(29) "Module successfully installed"
</pre><pre>string(52) "Something went wrong. Startup status is not changed."
</pre><pre>string(48) "Something went wrong. URL access is not changed."
</pre><pre>string(7) "Turn on"
</pre><pre>string(8) "Turn off"
</pre><pre>string(27) "Have not modules to install"
</pre><pre>string(15) "Widget creating"
</pre><pre>string(27) "Widget successfully created"
</pre><pre>string(19) "Enter template name"
</pre><pre>string(20) "No pages in category"
</pre><pre>string(27) "Category successfully added"
</pre><pre>string(8) "Discount"
</pre><pre>string(26) "You need to enter a string"
</pre><pre>string(23) "This field is required."
</pre><pre>string(6) "Please"
</pre><pre>string(23) "enter the correct value"
</pre><pre>string(27) "enter a valid email address"
</pre><pre>string(21) "enter the correct URL"
</pre><pre>string(18) "enter correct date"
</pre><pre>string(32) "enter correct date in format ISO"
</pre><pre>string(12) "enter number"
</pre><pre>string(18) "enter only numbers"
</pre><pre>string(32) "enter a valid credit card number"
</pre><pre>string(26) "enter the same value again"
</pre><pre>string(42) "Select the file with the correct extension"
</pre><pre>string(13) "Enter no more"
</pre><pre>string(10) "characters"
</pre><pre>string(14) "enter at least"
</pre><pre>string(16) "enter value from"
</pre><pre>string(2) "to"
</pre><pre>string(17) "enter number from"
</pre><pre>string(36) "enter a number less than or equal to"
</pre><pre>string(36) "enter a number more than or equal to"
</pre><pre>string(15) "Administer shop"
</pre><pre>string(18) "Back to the system"
</pre><pre>string(16) "Conversion error"
</pre><pre>string(64) "User already notified via E-mail upon availability! Notify again"
</pre><pre>string(44) "Notify the user via E-mail upon availability"
</pre><pre>string(22) "Error removing options"
</pre><pre>string(22) "Delete canceled orders"
</pre><pre>string(24) "Delete canceled messages"
</pre><pre>string(15) "Delete order ID"
</pre><pre>string(15) "Product changes"
</pre><pre>string(7) "Success"
</pre><pre>string(20) "File is loaded. Slot"
</pre><pre>string(35) "Script error. Notify administrator."
</pre><pre>string(22) "Wait for resize ending"
</pre><pre>string(26) "Resize images for products"
</pre><pre>string(20) "All finding products"
</pre><pre>string(9) "Processed"
</pre><pre>string(14) "Images updated"
</pre><pre>string(9) "Completed"
</pre><pre>string(22) "Resize products images"
</pre><pre>string(14) "Products found"
</pre><pre>string(24) "Additional images resize"
</pre><pre>string(37) "Found products with additional images"
</pre><pre>string(13) "Access denied"
</pre><pre>string(130) "This is a demo version ImageCMS. Part of the actions are limited. For a complete functional download and install the distribution."
</pre><pre>string(7) "Message"
</pre><pre>string(30) "Please enter the column number"
</pre><pre>string(21) "Column number updated"
</pre><pre>string(34) "Failed to update the column number"
</pre><pre>string(7) "Product"
</pre><pre>string(7) "Variant"
</pre><pre>string(5) "Price"
</pre><pre>string(7) "Balance"
</pre><pre>string(12) "Out of stock"
</pre><pre>string(11) "Add to Cart"
</pre><pre>string(11) "In the cart"
</pre><pre>string(37) "A user with this email already exists"
</pre><pre>string(16) "New user created"
</pre><pre>string(21) "Failed to create user"
</pre><pre>string(53) "Check the input data and fill in all mandatory fields"
</pre><pre>string(29) "Current certificate (amount):"
</pre><pre>string(19) "Sort method updated"
</pre><pre>string(18) "Conversion error, "
</pre><pre>string(25) "Failure to remove variant"
</pre><pre>string(23) "Remove selected orders?"
</pre><pre>string(30) "Remove selected notifications?"
</pre><pre>string(22) "Remove order with ID: "
</pre><pre>string(14) "Change product"
</pre><pre>string(25) "The file is loaded. Slot "
</pre><pre>string(52) "Error in the script. Please notify the administrator"
</pre><pre>string(24) "Short widget description"
</pre><pre>string(58) "To use your personal account, activate JavaScript, please."
</pre><pre>string(5) "Hello"
</pre><pre>string(8) "Contents"
</pre><pre>string(18) "Without a category"
</pre><pre>string(17) "Field constructor"
</pre><pre>string(4) "Menu"
</pre><pre>string(10) "Management"
</pre><pre>string(6) "Search"
</pre><pre>string(7) "Widgets"
</pre><pre>string(6) "System"
</pre><pre>string(13) "Site settings"
</pre><pre>string(49) "Clear old or Delete outdated posts or information"
</pre><pre>string(13) "Event journal"
</pre><pre>string(14) "Backup copying"
</pre><pre>string(11) "View a site"
</pre><pre>string(4) "Exit"
</pre><pre>string(17) "Username or Email"
</pre><pre>string(4) "Send"
</pre><pre>string(10) "Roles list"
</pre><pre>string(8) "New Role"
</pre><pre>string(4) "Role"
</pre><pre>string(13) "System update"
</pre><pre>string(9) "Attention"
</pre><pre>string(44) "Make a database backup copy before updating "
</pre><pre>string(41) "For example: /domains/mysite/public_html/"
</pre><pre>string(9) "Role edit"
</pre><pre>string(13) "Create a page"
</pre><pre>string(9) "New pages"
</pre><pre>string(13) "Updated pages"
</pre><pre>string(11) "Information"
</pre><pre>string(10) "Statistics"
</pre><pre>string(5) "Pages"
</pre><pre>string(6) "Folder"
</pre><pre>string(10) "Identifier"
</pre><pre>string(8) "Template"
</pre><pre>string(7) "Go back"
</pre><pre>string(11) "Module name"
</pre><pre>string(22) "This field is required"
</pre><pre>string(22) "Please fix this field."
</pre><pre>string(28) "Enter a valid email address."
</pre><pre>string(25) "Please enter a valid URL."
</pre><pre>string(26) "Please enter a valid date."
</pre><pre>string(32) "Please enter a valid date (ISO)."
</pre><pre>string(28) "Please enter a valid number."
</pre><pre>string(25) "Please enter only digits."
</pre><pre>string(40) "Please enter a valid credit card number."
</pre><pre>string(34) "Please enter the same value again."
</pre><pre>string(44) "Please enter a value with a valid extension."
</pre><pre>string(41) "Please enter no more than {0} characters."
</pre><pre>string(37) "Please enter at least {0} characters."
</pre><pre>string(57) "Please enter a value between {0} and {1} characters long."
</pre><pre>string(41) "Please enter a value between {0} and {1}."
</pre><pre>string(47) "Please enter a value less than or equal to {0}."
</pre><pre>string(50) "Please enter a value greater than or equal to {0}."
</pre><pre>string(4) "User"
</pre><pre>string(9) "Reference"
</pre><pre>string(6) "Active"
</pre><pre>string(17) "go to the website"
</pre><pre>string(4) "show"
</pre><pre>string(3) "hit"
</pre><pre>string(7) "novelty"
</pre><pre>string(9) "promotion"
</pre><pre>string(8) "Variants"
</pre><pre>string(20) "Drag product variant"
</pre><pre>string(31) "No relevant data has been found"
</pre><pre>string(9) "Telephone"
</pre><pre>string(15) "Delete products"
</pre><pre>string(32) "Really delete selected products?"
</pre><pre>string(13) "Move products"
</pre><pre>string(13) "Products list"
</pre><pre>string(12) "Reset filter"
</pre><pre>string(13) "Cancel filter"
</pre><pre>string(4) "Mark"
</pre><pre>string(3) "Hit"
</pre><pre>string(3) "New"
</pre><pre>string(9) "Promotion"
</pre><pre>string(16) "Move to category"
</pre><pre>string(7) "Article"
</pre><pre>string(3) "Yes"
</pre><pre>string(4) "From"
</pre><pre>string(2) "To"
</pre><pre>string(24) "Request showed no result"
</pre><pre>string(66) "There are no results. Modify your search or click the Reset Filter"
</pre><pre>string(20) "At the products page"
</pre><pre>string(6) "Change"
</pre><pre>string(7) "Options"
</pre><pre>string(7) "Specify"
</pre><pre>string(2) "or"
</pre><pre>string(4) "Item"
</pre><pre>string(8) "inactive"
</pre><pre>string(14) "Special offers"
</pre><pre>string(12) "Search start"
</pre><pre>string(5) "Brand"
</pre><pre>string(28) "Save and create a new record"
</pre><pre>string(14) " Save and edit"
</pre><pre>string(4) "View"
</pre><pre>string(10) " callbacks"
</pre><pre>string(14) "Sort by number"
</pre><pre>string(14) "Sort by name ."
</pre><pre>string(9) "User name"
</pre><pre>string(20) "Sort by phone number"
</pre><pre>string(13) "Sort by theme"
</pre><pre>string(5) "Theme"
</pre><pre>string(14) "Sort by status"
</pre><pre>string(12) "Sort by date"
</pre><pre>string(4) "Date"
</pre><pre>string(32) "Last comment left by the manager"
</pre><pre>string(7) "Manager"
</pre><pre>string(13) "Edit callback"
</pre><pre>string(14) "All Callbacks "
</pre><pre>string(13) "Found results"
</pre><pre>string(20) "Empty callback list."
</pre><pre>string(15) "Remove callback"
</pre><pre>string(25) "Really delete callback(s)"
</pre><pre>string(6) "Remove"
</pre><pre>string(18) "Empty status list."
</pre><pre>string(22) "Browse topics callback"
</pre><pre>string(13) "Create status"
</pre><pre>string(10) "By default"
</pre><pre>string(19) "Edit topic callback"
</pre><pre>string(26) "Creating a status callback"
</pre><pre>string(33) "Status set for all new requests. "
</pre><pre>string(19) "Editing by collback"
</pre><pre>string(21) "Editing Tools colback"
</pre><pre>string(70) "This icon denotes a field that can be translate well another language."
</pre><pre>string(31) "Creation of the request subject"
</pre><pre>string(22) "Browse topics collback"
</pre><pre>string(15) "Add a new topic"
</pre><pre>string(4) "Text"
</pre><pre>string(23) "Request subject editing"
</pre><pre>string(26) "List of callbacks is empty"
</pre><pre>string(16) "Callback editing"
</pre><pre>string(7) "Comment"
</pre><pre>string(16) "Date of creation"
</pre><pre>string(25) "Product property creating"
</pre><pre>string(46) "The field must contain only Latin characters ."
</pre><pre>string(4) "Hint"
</pre><pre>string(17) "Delete a property"
</pre><pre>string(27) "Remove selected properties?"
</pre><pre>string(22) "Properties list review"
</pre><pre>string(17) "Create a property"
</pre><pre>string(19) "Empty property list"
</pre><pre>string(22) "At the properties page"
</pre><pre>string(15) "Products import"
</pre><pre>string(4) "File"
</pre><pre>string(11) "Import type"
</pre><pre>string(7) "Catalog"
</pre><pre>string(7) "Columns"
</pre><pre>string(19) "The field separator"
</pre><pre>string(9) "Semicolon"
</pre><pre>string(5) "Colon"
</pre><pre>string(5) "Comma"
</pre><pre>string(3) "Tab"
</pre><pre>string(5) "Sharp"
</pre><pre>string(14) "Text separator"
</pre><pre>string(6) "quotes"
</pre><pre>string(13) "Single quotes"
</pre><pre>string(8) "Encoding"
</pre><pre>string(6) "Import"
</pre><pre>string(13) "Products name"
</pre><pre>string(9) "Old price"
</pre><pre>string(8) "Quantity"
</pre><pre>string(12) "Variant name"
</pre><pre>string(16) "Related products"
</pre><pre>string(14) "The main image"
</pre><pre>string(26) "Main picture an additional"
</pre><pre>string(11) "Small image"
</pre><pre>string(25) "Small image an additional"
</pre><pre>string(17) "Additional images"
</pre><pre>string(17) "Short description"
</pre><pre>string(11) "Skip column"
</pre><pre>string(16) "Import completed"
</pre><pre>string(16) "Fields separator"
</pre><pre>string(6) "Quotes"
</pre><pre>string(15) "Field separator"
</pre><pre>string(12) "Product Name"
</pre><pre>string(10) "Main image"
</pre><pre>string(11) "small image"
</pre><pre>string(15) "Import Complete"
</pre><pre>string(10) "Attributes"
</pre><pre>string(44) "The list of attributes that will be imported"
</pre><pre>string(21) "Import-Export CSV/XLS"
</pre><pre>string(6) "Export"
</pre><pre>string(15) "Select the file"
</pre><pre>string(38) "Select the file in a convenient format"
</pre><pre>string(5) "Files"
</pre><pre>string(54) "The data of your database will be stored in the folder"
</pre><pre>string(44) "Take a snapshot of the database before start"
</pre><pre>string(6) "Resize"
</pre><pre>string(43) "For imported images will be produced resize"
</pre><pre>string(21) "It may take more time"
</pre><pre>string(32) "Start resize images after import"
</pre><pre>string(14) "Price checking"
</pre><pre>string(77) "Will be recalculated prices of products in accordance to the default currency"
</pre><pre>string(27) "Refresh prices after import"
</pre><pre>string(16) "Import language "
</pre><pre>string(12) "Start import"
</pre><pre>string(15) "Products export"
</pre><pre>string(6) "active"
</pre><pre>string(15) "Export complete"
</pre><pre>string(10) "categories"
</pre><pre>string(18) "Loading properties"
</pre><pre>string(42) "Show properties of the selected categories"
</pre><pre>string(26) "Properties of the products"
</pre><pre>string(28) "Select a category for export"
</pre><pre>string(8) "Filetype"
</pre><pre>string(19) "Exports in progress"
</pre><pre>string(12) "Start export"
</pre><pre>string(22) "Category list is empty"
</pre><pre>string(11) "Translation"
</pre><pre>string(13) "Drug category"
</pre><pre>string(17) "Collapse category"
</pre><pre>string(19) "expand the category"
</pre><pre>string(17) "Edit the category"
</pre><pre>string(17) "Category creating"
</pre><pre>string(12) "Select image"
</pre><pre>string(21) "Create a new template"
</pre><pre>string(49) "The basic template category. Default category.tpl"
</pre><pre>string(13) "Autoselection"
</pre><pre>string(14) "-Not selected-"
</pre><pre>string(10) "By raiting"
</pre><pre>string(23) "From cheap to expensive"
</pre><pre>string(23) "From expensive to cheap"
</pre><pre>string(7) "Popular"
</pre><pre>string(7) "Novelty"
</pre><pre>string(10) "Promotions"
</pre><pre>string(34) "Do not show short name of the site"
</pre><pre>string(9) "Meta data"
</pre><pre>string(18) "Product categories"
</pre><pre>string(35) "There are no categories at the site"
</pre><pre>string(15) "Category delete"
</pre><pre>string(26) "Remove selected categories"
</pre><pre>string(63) "Attention! will also remove all the products from this category"
</pre><pre>string(16) "Edit category ID"
</pre><pre>string(12) "Not selected"
</pre><pre>string(20) "Creating a warehouse"
</pre><pre>string(7) "Address"
</pre><pre>string(16) "Delete warehouse"
</pre><pre>string(34) "Really remove selected warehouses?"
</pre><pre>string(17) "Delete warehouses"
</pre><pre>string(15) "Warehouses list"
</pre><pre>string(18) "Create a warehouse"
</pre><pre>string(21) "Empty warehouse list."
</pre><pre>string(14) "Edit warehouse"
</pre><pre>string(26) "Creation of Status pending"
</pre><pre>string(19) "General information"
</pre><pre>string(15) "Removing status"
</pre><pre>string(19) "Remove your status?"
</pre><pre>string(14) "Remove status?"
</pre><pre>string(29) "View the status of appearance"
</pre><pre>string(28) "Editing status of appearance"
</pre><pre>string(20) "Callback status data"
</pre><pre>string(22) "Delivery method create"
</pre><pre>string(4) "Data"
</pre><pre>string(26) "Description delivery price"
</pre><pre>string(14) "Delivery price"
</pre><pre>string(4) "Free"
</pre><pre>string(4) "from"
</pre><pre>string(14) "Payment method"
</pre><pre>string(14) "List is empty."
</pre><pre>string(29) "Removing the shipping methods"
</pre><pre>string(36) "Delete Selected methods of delivery?"
</pre><pre>string(26) "Delete method of delivery?"
</pre><pre>string(21) "Delivery methods list"
</pre><pre>string(23) "Create a way to deliver"
</pre><pre>string(30) "Delivery methods list is empty"
</pre><pre>string(20) "Delivery and payment"
</pre><pre>string(20) "Delivery method edit"
</pre><pre>string(13) "List is empty"
</pre><pre>string(13) "Product order"
</pre><pre>string(12) "Product name"
</pre><pre>string(16) "Measurement unit"
</pre><pre>string(11) "Total price"
</pre><pre>string(7) "Pieces."
</pre><pre>string(16) "Delivery Address"
</pre><pre>string(5) "Phone"
</pre><pre>string(12) "Order create"
</pre><pre>string(10) "Make order"
</pre><pre>string(14) "Find a product"
</pre><pre>string(19) "Article / Name / ID"
</pre><pre>string(5) "Total"
</pre><pre>string(10) "Create new"
</pre><pre>string(15) "Create new user"
</pre><pre>string(9) "Full Name"
</pre><pre>string(11) "Search user"
</pre><pre>string(22) "ID / Full Name / Email"
</pre><pre>string(10) "Editing by"
</pre><pre>string(17) "Order information"
</pre><pre>string(5) "Email"
</pre><pre>string(15) "Products amount"
</pre><pre>string(11) "Certificate"
</pre><pre>string(13) "Enter the key"
</pre><pre>string(16) "Current discount"
</pre><pre>string(13) "Order removal"
</pre><pre>string(24) " Delete selected orders?"
</pre><pre>string(11) "Orders list"
</pre><pre>string(13) "Change status"
</pre><pre>string(14) "Payment status"
</pre><pre>string(4) "Paid"
</pre><pre>string(8) "Not paid"
</pre><pre>string(12) "Create order"
</pre><pre>string(8) "Customer"
</pre><pre>string(13) "(no delivery)"
</pre><pre>string(12) "numbers only"
</pre><pre>string(13) "choose a date"
</pre><pre>string(10) "Edit order"
</pre><pre>string(17) "Purchased Product"
</pre><pre>string(3) "pcs"
</pre><pre>string(18) "Orders on the page"
</pre><pre>string(108) " This product has been deleted from the shop! You can only change the quantity or replace by another product"
</pre><pre>string(49) "Product price has been changed. Old product price"
</pre><pre>string(20) "Save the old price ?"
</pre><pre>string(38) "Notify a buyer about the status change"
</pre><pre>string(8) "Complete"
</pre><pre>string(2) "on"
</pre><pre>string(3) "map"
</pre><pre>string(11) "Show on map"
</pre><pre>string(15) "Additional data"
</pre><pre>string(15) "Delivery Method"
</pre><pre>string(5) "Order"
</pre><pre>string(16) "Has been created"
</pre><pre>string(13) "Print receipt"
</pre><pre>string(10) "Basic data"
</pre><pre>string(26) "Products and order history"
</pre><pre>string(13) "Date of order"
</pre><pre>string(13) "Not specified"
</pre><pre>string(12) "Order amount"
</pre><pre>string(8) "Delivery"
</pre><pre>string(14) "Full user name"
</pre><pre>string(13) "Items in Cart"
</pre><pre>string(16) "Gift Certificate"
</pre><pre>string(30) "Add a new product to the order"
</pre><pre>string(20) "Ordering information"
</pre><pre>string(31) "Commentary to change the status"
</pre><pre>string(30) "Info buyer about change status"
</pre><pre>string(13) "Date modified"
</pre><pre>string(14) "Status history"
</pre><pre>string(16) "Product addition"
</pre><pre>string(3) "Add"
</pre><pre>string(2) "in"
</pre><pre>string(4) "Cart"
</pre><pre>string(2) "Me"
</pre><pre>string(6) "Option"
</pre><pre>string(8) "Payments"
</pre><pre>string(6) "Result"
</pre><pre>string(22) "Orders status creating"
</pre><pre>string(11) "Edit status"
</pre><pre>string(21) "Order status deleting"
</pre><pre>string(24) "Delete order status(es)?"
</pre><pre>string(6) "exists"
</pre><pre>string(11) "In order to"
</pre><pre>string(40) "Do you really want to delete the status?"
</pre><pre>string(35) "Set another status for these orders"
</pre><pre>string(34) "Delete all orders with this status"
</pre><pre>string(18) "Orders status edit"
</pre><pre>string(10) "New orders"
</pre><pre>string(11) "Bestsellers"
</pre><pre>string(9) "New users"
</pre><pre>string(6) "Amount"
</pre><pre>string(27) "Amount of additions to Cart"
</pre><pre>string(20) "Date of registration"
</pre><pre>string(13) "Last comments"
</pre><pre>string(12) "Date Created"
</pre><pre>string(8) "Approved"
</pre><pre>string(20) "Waiting for approval"
</pre><pre>string(4) "Spam"
</pre><pre>string(16) "News of ImageCMS"
</pre><pre>string(8) "Read all"
</pre><pre>string(21) "Payment method create"
</pre><pre>string(26) "Removal of payment methods"
</pre><pre>string(36) "Delete the selected payment methods?"
</pre><pre>string(25) "Delete method of payment?"
</pre><pre>string(20) "Payment methods list"
</pre><pre>string(23) "Create a payment method"
</pre><pre>string(13) "Currency name"
</pre><pre>string(15) "Currency symbol"
</pre><pre>string(29) "Payment methods list is empty"
</pre><pre>string(19) "Payment method edit"
</pre><pre>string(23) "Additional field create"
</pre><pre>string(6) "Entity"
</pre><pre>string(7) "Orders "
</pre><pre>string(53) "The field should only contain letters without numbers"
</pre><pre>string(5) "Label"
</pre><pre>string(5) "Field"
</pre><pre>string(8) "Required"
</pre><pre>string(7) "Private"
</pre><pre>string(10) "Field type"
</pre><pre>string(15) "Possible values"
</pre><pre>string(10) "Validators"
</pre><pre>string(128) "Snippet of a certain format,<br /> verifies syntactic correctness<br /> of the entered information - that is,<br /> to validate."
</pre><pre>string(7) "Classes"
</pre><pre>string(25) "Custom classes for widget"
</pre><pre>string(13) "Access rights"
</pre><pre>string(179) "Access rights define <br />a set of actions (eg, read,<br /> write, execute) permissions for<br /> the subjects (for example, users<br /> of the system) of <br />the data objects."
</pre><pre>string(5) "Close"
</pre><pre>string(13) "Remove fields"
</pre><pre>string(26) "Remove the selected field?"
</pre><pre>string(17) "Remove the field?"
</pre><pre>string(22) "Additional fields list"
</pre><pre>string(12) "Create Field"
</pre><pre>string(8) "One user"
</pre><pre>string(14) "Related entity"
</pre><pre>string(22) "Editing a custom field"
</pre><pre>string(21) "Additional field data"
</pre><pre>string(12) "Field Active"
</pre><pre>string(16) "Roles group edit"
</pre><pre>string(11) "Role create"
</pre><pre>string(9) "No orders"
</pre><pre>string(12) "Remove group"
</pre><pre>string(21) "Create group of roles"
</pre><pre>string(22) "Products without icons"
</pre><pre>string(7) "Delete "
</pre><pre>string(13) "Notification "
</pre><pre>string(5) "ID : "
</pre><pre>string(78) "User has already been notified by e-mail about product arrival! Notify again? "
</pre><pre>string(46) "Notify a user by e-mail about product arrival?"
</pre><pre>string(43) " Change the status of marked notifications?"
</pre><pre>string(16) "Removal requests"
</pre><pre>string(28) "Delete the selected queries?"
</pre><pre>string(17) "Delete the query?"
</pre><pre>string(20) "Arrival notification"
</pre><pre>string(16) "Time of addition"
</pre><pre>string(11) "Valid until"
</pre><pre>string(13) "Notifications"
</pre><pre>string(14) "Notified email"
</pre><pre>string(8) "Notified"
</pre><pre>string(6) "Notify"
</pre><pre>string(40) "Empty product arrival notification list."
</pre><pre>string(28) "The request for notification"
</pre><pre>string(2) "by"
</pre><pre>string(19) "Status has been set"
</pre><pre>string(19) "E-mail notification"
</pre><pre>string(6) "Select"
</pre><pre>string(16) "Product creation"
</pre><pre>string(6) "Images"
</pre><pre>string(4) "Kits"
</pre><pre>string(20) "Product variant name"
</pre><pre>string(5) "Photo"
</pre><pre>string(4) "Edit"
</pre><pre>string(18) "Load from internet"
</pre><pre>string(13) "Add a variant"
</pre><pre>string(10) "Brand name"
</pre><pre>string(21) "Additional categories"
</pre><pre>string(10) "Warehouses"
</pre><pre>string(45) "Product main template. By default product.tpl"
</pre><pre>string(19) "Product variations "
</pre><pre>string(7) "product"
</pre><pre>string(9) "Selected "
</pre><pre>string(23) " Create a product copy?"
</pre><pre>string(20) "Product displacement"
</pre><pre>string(16) "Create a product"
</pre><pre>string(10) "Sort by ID"
</pre><pre>string(13) "Sort by price"
</pre><pre>string(4) "Copy"
</pre><pre>string(8) "Previous"
</pre><pre>string(13) "Select a file"
</pre><pre>string(18) "Create small image"
</pre><pre>string(26) "Another main image variant"
</pre><pre>string(27) "Another small image variant"
</pre><pre>string(12) "Create a set"
</pre><pre>string(10) "Delete set"
</pre><pre>string(27) "Kit List products are empty"
</pre><pre>string(11) "Kit removal"
</pre><pre>string(13) "Kits del body"
</pre><pre>string(6) "status"
</pre><pre>string(11) "Select file"
</pre><pre>string(36) "Searching for images on the Internet"
</pre><pre>string(25) "URL or request for search"
</pre><pre>string(50) "Enter the URL of the image or the search criterion"
</pre><pre>string(41) "Hold down Shift to select multiple images"
</pre><pre>string(18) "Save as additional"
</pre><pre>string(43) "Do you really want to delete selected kits?"
</pre><pre>string(19) "Product kits review"
</pre><pre>string(12) "main product"
</pre><pre>string(12) "Main product"
</pre><pre>string(17) "Attached products"
</pre><pre>string(18) "Create product kit"
</pre><pre>string(14) "Added products"
</pre><pre>string(16) "Edit product kit"
</pre><pre>string(9) "Message: "
</pre><pre>string(23) "Changes have been saved"
</pre><pre>string(6) "Error "
</pre><pre>string(29) "The absolute path to the page"
</pre><pre>string(15) "Banner creation"
</pre><pre>string(11) "Text banner"
</pre><pre>string(25) "Display on the home page:"
</pre><pre>string(25) "Display in the categories"
</pre><pre>string(14) "Do not display"
</pre><pre>string(10) "Select all"
</pre><pre>string(12) "Active until"
</pre><pre>string(15) "Removing banner"
</pre><pre>string(24) "Remove selected banners?"
</pre><pre>string(15) "Remove banners?"
</pre><pre>string(11) "Banner list"
</pre><pre>string(15) "Create a banner"
</pre><pre>string(11) "On the main"
</pre><pre>string(13) "In categories"
</pre><pre>string(13) "Active before"
</pre><pre>string(18) "Empty banner list."
</pre><pre>string(14) "Editing banner"
</pre><pre>string(24) "Display on the home page"
</pre><pre>string(26) "Display in the categories:"
</pre><pre>string(20) "Translated brand ID:"
</pre><pre>string(12) "Create brand"
</pre><pre>string(14) "Removing brand"
</pre><pre>string(23) "Remove selected brands?"
</pre><pre>string(14) "Remove brands?"
</pre><pre>string(14) "List of brands"
</pre><pre>string(14) "Create a brand"
</pre><pre>string(21) "Brands list is empty."
</pre><pre>string(13) "Editing brand"
</pre><pre>string(17) "Brands statistics"
</pre><pre>string(17) "Orders statistics"
</pre><pre>string(18) "Total orders price"
</pre><pre>string(4) "Days"
</pre><pre>string(20) "The amount of orders"
</pre><pre>string(16) "Number of Orders"
</pre><pre>string(13) "Shop settings"
</pre><pre>string(13) "External view"
</pre><pre>string(32) "Integration with social networks"
</pre><pre>string(22) "Notifications in pages"
</pre><pre>string(28) "Discharge into Yandex.Market"
</pre><pre>string(28) "Products count shown on site"
</pre><pre>string(74) "The values ​​for the number of products per page (example: 12, 24, 48)"
</pre><pre>string(31) "Products count in control panel"
</pre><pre>string(17) "fractional digits"
</pre><pre>string(23) "The name at the website"
</pre><pre>string(3) "Get"
</pre><pre>string(31) "Prefix (folder will be created)"
</pre><pre>string(10) "Height, px"
</pre><pre>string(9) "Width, px"
</pre><pre>string(16) "Additional image"
</pre><pre>string(9) "Thumbnail"
</pre><pre>string(7) "Quality"
</pre><pre>string(9) "Main size"
</pre><pre>string(4) "Auto"
</pre><pre>string(6) "Height"
</pre><pre>string(5) "Width"
</pre><pre>string(9) "Watermark"
</pre><pre>string(22) " Horizontal alignment "
</pre><pre>string(4) "Left"
</pre><pre>string(6) "Center"
</pre><pre>string(5) "Right"
</pre><pre>string(18) "Vertical alignment"
</pre><pre>string(2) "Up"
</pre><pre>string(13) "In the middle"
</pre><pre>string(13) "At the bottom"
</pre><pre>string(60) "The ratio of the size of the watermark to the size of photos"
</pre><pre>string(17) "Path to the image"
</pre><pre>string(43) "The file must be on the server. For example"
</pre><pre>string(12) "Transparency"
</pre><pre>string(9) "Font size"
</pre><pre>string(11) "Font colour"
</pre><pre>string(12) "Displacement"
</pre><pre>string(13) "Path to font "
</pre><pre>string(52) "Font file must be located on the server. For example"
</pre><pre>string(33) "Perform resize of all the images?"
</pre><pre>string(27) "Including additional images"
</pre><pre>string(35) "Perform resize the selected product"
</pre><pre>string(9) "Wish List"
</pre><pre>string(6) "sender"
</pre><pre>string(7) "Subject"
</pre><pre>string(14) "Message format"
</pre><pre>string(12) "Message text"
</pre><pre>string(34) "You can use the following variable"
</pre><pre>string(27) "Name of the WishList author"
</pre><pre>string(40) " Telephone number of the wishlist author"
</pre><pre>string(31) "Comments of the wishlist author"
</pre><pre>string(24) "Key to view the wishlist"
</pre><pre>string(25) "Link to view the WishList"
</pre><pre>string(33) "IP address of the wishlist author"
</pre><pre>string(28) "Sending date of the wishlist"
</pre><pre>string(37) "Notification status about the arrival"
</pre><pre>string(37) " Name of the user who made a request "
</pre><pre>string(17) "User phone number"
</pre><pre>string(13) "Product name "
</pre><pre>string(24) "Link to view the product"
</pre><pre>string(31) " User notification request date"
</pre><pre>string(53) "Send notification about new callback to administrator"
</pre><pre>string(51) "Email for sending notifications about new Callbacks"
</pre><pre>string(29) "Username requested a callback"
</pre><pre>string(42) "User telephone number requested a callback"
</pre><pre>string(22) " Callback request date"
</pre><pre>string(27) "Comments by a callback user"
</pre><pre>string(16) "General settings"
</pre><pre>string(36) "User registartion after making order"
</pre><pre>string(48) "Recalculate products after payment of the order?"
</pre><pre>string(61) "Consider the amount of products warehouse on adding to basket"
</pre><pre>string(63) " Administrator notification about the order placement by e-mail"
</pre><pre>string(13) "Administrator"
</pre><pre>string(47) "Customer notification about the order placement"
</pre><pre>string(48) "Order placement e-mail to the user has been sent"
</pre><pre>string(20) "Name of the customer"
</pre><pre>string(23) "Customer e-mail address"
</pre><pre>string(21) "Customer phone number"
</pre><pre>string(42) "Delivery address specified by the customer"
</pre><pre>string(8) "ID order"
</pre><pre>string(22) " Key to view the order"
</pre><pre>string(18) " Link to the order"
</pre><pre>string(52) " Customer notification about the order status change"
</pre><pre>string(16) "New order status"
</pre><pre>string(31) "Time of the order status change"
</pre><pre>string(24) "Registration after order"
</pre><pre>string(26) " User login for site enrty"
</pre><pre>string(24) "Username of the customer"
</pre><pre>string(15) "Customer e-mail"
</pre><pre>string(17) "Customer password"
</pre><pre>string(12) "Site address"
</pre><pre>string(16) "Top sales block "
</pre><pre>string(32) " Popularity formula coefficient "
</pre><pre>string(98) " Popularity formula: number of views+ products added to the cart *coefficient . For example: 1000."
</pre><pre>string(17) "Password recovery"
</pre><pre>string(9) "Site name"
</pre><pre>string(33) "Link to confirm password recovery"
</pre><pre>string(3) "Key"
</pre><pre>string(20) "Site webmaster email"
</pre><pre>string(36) "Switch on integration with Facebook?"
</pre><pre>string(10) "Secret key"
</pre><pre>string(18) "Application number"
</pre><pre>string(22) "Select template folder"
</pre><pre>string(37) "Switch on integration with VKontakte?"
</pre><pre>string(14) "Protection key"
</pre><pre>string(21) "Message about arrival"
</pre><pre>string(24) "Message about a callback"
</pre><pre>string(27) "Message from the order page"
</pre><pre>string(22) "API Key for Mail Chimp"
</pre><pre>string(23) "Key for Mail Chimp list"
</pre><pre>string(22) "Settings Yandex.Market"
</pre><pre>string(30) "Displayed categories selection"
</pre><pre>string(22) "Yandex.Market document"
</pre><pre>string(12) "XML document"
</pre><pre>string(10) "don't show"
</pre><pre>string(15) "Currency create"
</pre><pre>string(3) "ISO"
</pre><pre>string(4) "Code"
</pre><pre>string(9) "Character"
</pre><pre>string(13) "Currency rate"
</pre><pre>string(15) "Remove currency"
</pre><pre>string(29) "Remove the selected currency?"
</pre><pre>string(13) "Recalculation"
</pre><pre>string(52) "The currency is in use in the products. Recalculate?"
</pre><pre>string(11) "Recalculate"
</pre><pre>string(19) "Removing properties"
</pre><pre>string(16) "Remove currency?"
</pre><pre>string(15) "Currencies list"
</pre><pre>string(12) "Check prices"
</pre><pre>string(15) "Create currency"
</pre><pre>string(19) "Additional currency"
</pre><pre>string(9) "Make main"
</pre><pre>string(22) "Make currency default "
</pre><pre>string(23) "There are no currencies"
</pre><pre>string(13) "Currency edit"
</pre><pre>string(28) "Creating cumulative discount"
</pre><pre>string(15) "These discounts"
</pre><pre>string(35) "Amount of which will be a discount."
</pre><pre>string(44) "The amount to which there will be a discount"
</pre><pre>string(10) "Not active"
</pre><pre>string(20) "Editing by discounts"
</pre><pre>string(9) "Full name"
</pre><pre>string(14) "Purchase price"
</pre><pre>string(20) "Off manually entered"
</pre><pre>string(18) "Removing discounts"
</pre><pre>string(25) "Remove selected discount?"
</pre><pre>string(20) "Remove the discount?"
</pre><pre>string(28) "List of cumulative discounts"
</pre><pre>string(17) "Create a discount"
</pre><pre>string(18) "Discount Amount of"
</pre><pre>string(18) "Discount Amount to"
</pre><pre>string(19) "Empty discount list"
</pre><pre>string(13) "Deposit rates"
</pre><pre>string(16) "Empty user list."
</pre><pre>string(17) "Editing discounts"
</pre><pre>string(16) "Discount options"
</pre><pre>string(15) "Member Discount"
</pre><pre>string(9) "Discounts"
</pre><pre>string(23) "Just like the number 10"
</pre><pre>string(25) "Removing Gift Certificate"
</pre><pre>string(34) "Remove selected gift certificates?"
</pre><pre>string(26) "Remove a gift certificate?"
</pre><pre>string(21) "Gift certificate list"
</pre><pre>string(23) "Create gift certificate"
</pre><pre>string(10) "Unique key"
</pre><pre>string(8) "Valid to"
</pre><pre>string(31) "Gift certificate list is empty."
</pre><pre>string(23) "Gift certificate create"
</pre><pre>string(22) "Gift certificate price"
</pre><pre>string(8) "Generate"
</pre><pre>string(25) "Gift certificate settings"
</pre><pre>string(22) "Use gift certificates?"
</pre><pre>string(21) "Gift certificate edit"
</pre><pre>string(28) "This discount does not enjoy"
</pre><pre>string(13) "Starting date"
</pre><pre>string(15) "Finishing date "
</pre><pre>string(61) " Number greater than zero. To use a percent discount apply : "
</pre><pre>string(29) "Enter a product for promotion"
</pre><pre>string(20) "Enter the name or id"
</pre><pre>string(18) "Selected products:"
</pre><pre>string(29) "Follow product ID by a comma."
</pre><pre>string(10) "User group"
</pre><pre>string(31) "There are no translations users"
</pre><pre>string(18) "Unregistered users"
</pre><pre>string(27) "List of permanent discounts"
</pre><pre>string(28) "Enter a product for discount"
</pre><pre>string(11) "Create user"
</pre><pre>string(15) "Deleting a user"
</pre><pre>string(22) "Remove selected users?"
</pre><pre>string(20) "Time of registration"
</pre><pre>string(11) "Simple user"
</pre><pre>string(71) "Export CSV gives <br />jumps file with <br />a list of all<br /> users."
</pre><pre>string(14) "Orders history"
</pre><pre>string(17) "Time of the order"
</pre><pre>string(12) "Delete order"
</pre><pre>string(9) "User data"
</pre><pre>string(8) "WishList"
</pre><pre>string(3) "Pcs"
</pre><pre>string(9) "File name"
</pre><pre>string(6) "Source"
</pre><pre>string(4) "Lock"
</pre><pre>string(8) "No files"
</pre><pre>string(12) "Autocleaning"
</pre><pre>string(3) "Off"
</pre><pre>string(2) "On"
</pre><pre>string(61) "Warning! Files will be deleted automaticly on backup creating"
</pre><pre>string(17) "Delete after date"
</pre><pre>string(5) "month"
</pre><pre>string(19) "Maximum backup size"
</pre><pre>string(18) "Update information"
</pre><pre>string(17) "BackUp and Update"
</pre><pre>string(15) "Current version"
</pre><pre>string(11) "New version"
</pre><pre>string(15) "Date of release"
</pre><pre>string(31) "You have actual system version."
</pre><pre>string(9) "Date/time"
</pre><pre>string(6) "Action"
</pre><pre>string(13) "Language edit"
</pre><pre>string(6) "Locale"
</pre><pre>string(9) "Image URL"
</pre><pre>string(15) "Choose an image"
</pre><pre>string(26) "Copy to the local computer"
</pre><pre>string(18) "Save on the server"
</pre><pre>string(35) "File will be saved in the directory"
</pre><pre>string(10) "Send email"
</pre><pre>string(11) "File format"
</pre><pre>string(30) "The creation of a new language"
</pre><pre>string(14) "Module install"
</pre><pre>string(16) "General Settings"
</pre><pre>string(17) "Analysts settings"
</pre><pre>string(23) "Management of Meta Tags"
</pre><pre>string(15) "Enter Meta Tags"
</pre><pre>string(16) "Site information"
</pre><pre>string(13) "Site shutdown"
</pre><pre>string(52) "The site will be available only to the Administrator"
</pre><pre>string(21) "Select admin language"
</pre><pre>string(36) "Display category tree in the content"
</pre><pre>string(11) "Text editor"
</pre><pre>string(19) "ID Google Analytics"
</pre><pre>string(44) "The code should be in the format ua-54545845"
</pre><pre>string(12) "Ya.Webmaster"
</pre><pre>string(20) "ID for yandex metric"
</pre><pre>string(4) "Page"
</pre><pre>string(50) "Whether to display the site name in the title page"
</pre><pre>string(13) "Category name"
</pre><pre>string(54) "Whether to display the category name in the title page"
</pre><pre>string(9) "Separator"
</pre><pre>string(14) "Auto formation"
</pre><pre>string(11) "Leave empty"
</pre><pre>string(25) "If not given or specified"
</pre><pre>string(16) "If not specified"
</pre><pre>string(15) "Choose language"
</pre><pre>string(15) "Short site name"
</pre><pre>string(8) "Keywords"
</pre><pre>string(49) "Please use function siteinfo() with the parameter"
</pre><pre>string(12) "Company type"
</pre><pre>string(10) "Main phone"
</pre><pre>string(11) "Admin email"
</pre><pre>string(8) "Contacts"
</pre><pre>string(34) "that you entered as a contact type"
</pre><pre>string(12) "Contact type"
</pre><pre>string(5) "Value"
</pre><pre>string(29) "you entered as a contact type"
</pre><pre>string(11) "Add contact"
</pre><pre>string(4) "Logo"
</pre><pre>string(25) "Click to select the image"
</pre><pre>string(5) "Basic"
</pre><pre>string(15) "Delete category"
</pre><pre>string(15) "Create category"
</pre><pre>string(7) "message"
</pre><pre>string(32) "Module search is being developed"
</pre><pre>string(64) "set write rights on the directory for simple module installation"
</pre><pre>string(7) "Actions"
</pre><pre>string(42) "No modules have been found at your request"
</pre><pre>string(13) "Module search"
</pre><pre>string(62) "Here you can search for modules and set them to automatic mode"
</pre><pre>string(11) "G.Webmaster"
</pre><pre>string(7) "Page ID"
</pre><pre>string(44) "Error: Module information has not been found"
</pre><pre>string(37) "FTP_connect function is not available"
</pre><pre>string(51) "Server connection error:Check username and password"
</pre><pre>string(32) "Wrong path to the root directory"
</pre><pre>string(22) "File downloading error"
</pre><pre>string(47) "Creation of temporary directory has been failed"
</pre><pre>string(32) "Delete the directory to continue"
</pre><pre>string(20) "Attention or Caution"
</pre><pre>string(15) "Exploding error"
</pre><pre>string(25) "Module installation error"
</pre><pre>string(24) "Modul has been installed"
</pre><pre>string(26) "Module installation module"
</pre><pre>string(10) "First link"
</pre><pre>string(9) "Last link"
</pre><pre>string(18) "Installed a module"
</pre><pre>string(16) "Deleted a module"
</pre><pre>string(33) "The module successfully uninstall"
</pre><pre>string(21) "Module deletion error"
</pre><pre>string(27) "Changed the module settings"
</pre><pre>string(8) "Version "
</pre><pre>string(27) "Can't load module info file"
</pre><pre>string(17) "Positions updated"
</pre><pre>string(4) "Fail"
</pre><pre>string(13) "Changes saved"
</pre><pre>string(4) "Prev"
</pre><pre>string(17) "Cleared the cache"
</pre><pre>string(13) "Files deleted"
</pre><pre>string(22) "Cache has been cleared"
</pre><pre>string(32) "Outdated files have been deleted"
</pre><pre>string(20) "Clearing cache error"
</pre><pre>string(24) "exited the control panel"
</pre><pre>string(4) "page"
</pre><pre>string(10) "ip-address"
</pre><pre>string(9) "user name"
</pre><pre>string(41) "An error occurred while sending a message"
</pre><pre>string(26) "Your message has been sent"
</pre><pre>string(27) "Comment is a required field"
</pre><pre>string(15) "Deleted ID page"
</pre><pre>string(46) "The %s field can only contain Latin characters"
</pre><pre>string(12) "Description "
</pre><pre>string(13) "Creation time"
</pre><pre>string(16) "Publication date"
</pre><pre>string(16) "Publication time"
</pre><pre>string(18) "Main page template"
</pre><pre>string(29) "From validation error: <br />"
</pre><pre>string(29) "Reserved the same name module"
</pre><pre>string(34) "Reserved of the same name category"
</pre><pre>string(74) "Page with the same URL has been created yet. Specify or select another URL"
</pre><pre>string(14) "Created a page"
</pre><pre>string(21) "Page has been created"
</pre><pre>string(9) "Not found"
</pre><pre>string(20) "Language of the page"
</pre><pre>string(19) "Main page template "
</pre><pre>string(13) "Page with URL"
</pre><pre>string(14) "in ID category"
</pre><pre>string(46) " already exists. Specify or select another URL"
</pre><pre>string(16) "Changed the page"
</pre><pre>string(31) "Page contents have been updated"
</pre><pre>string(39) "Error: Generic page can not be deleted."
</pre><pre>string(22) "Page has been deleted."
</pre><pre>string(17) "Successful delete"
</pre><pre>string(18) "Successfull moving"
</pre><pre>string(19) "The operation error"
</pre><pre>string(18) "Zero-length string"
</pre><pre>string(21) "Status change success"
</pre><pre>string(15) "Protection code"
</pre><pre>string(28) "Entered the IP control panel"
</pre><pre>string(41) "Username and password have not been found"
</pre><pre>string(77) "Please check your email for instructions on how to activate the new password."
</pre><pre>string(21) "Wrong protection code"
</pre><pre>string(35) "PHP SOAP extension is not installed"
</pre><pre>string(17) "Changes not saved"
</pre><pre>string(65) "Set the directory access rights to continue the work with widgets"
</pre><pre>string(71) "Widget with the same name already exists. Choose or select another name"
</pre><pre>string(6) "Method"
</pre><pre>string(16) "Created a widget"
</pre><pre>string(14) "Widget created"
</pre><pre>string(24) "Error: widget not found!"
</pre><pre>string(16) "Changed a widget"
</pre><pre>string(22) "Changes has been saved"
</pre><pre>string(16) "Deleted a widget"
</pre><pre>string(27) "Widget successfully deleted"
</pre><pre>string(4) "Core"
</pre><pre>string(32) "You are using the latest version"
</pre><pre>string(16) "Congratulations!"
</pre><pre>string(40) "Error: Wrong path to the root directory."
</pre><pre>string(29) "Error downloading update file"
</pre><pre>string(27) "Updating has been completed"
</pre><pre>string(17) "Create a language"
</pre><pre>string(25) "Language has been created"
</pre><pre>string(18) "Changed a language"
</pre><pre>string(61) "This language has been used by default and can not be deleted"
</pre><pre>string(8) "Blocking"
</pre><pre>string(23) "Deleted the ID language"
</pre><pre>string(29) "the language has been deleted"
</pre><pre>string(43) "Specified a language or selected a language"
</pre><pre>string(42) "The language has been installed by default"
</pre><pre>string(10) "Short name"
</pre><pre>string(23) "Page has not been found"
</pre><pre>string(23) "Changed wesite settings"
</pre><pre>string(24) "Settings have been saved"
</pre><pre>string(26) "Some of settings not saved"
</pre><pre>string(14) "Settings saved"
</pre><pre>string(57) "Directory ./application/backups has no writing permission"
</pre><pre>string(33) "Backup copying has been completed"
</pre><pre>string(40) "The position has been successfully saved"
</pre><pre>string(14) "URL categories"
</pre><pre>string(8) "Per page"
</pre><pre>string(47) "Category has been created or created a category"
</pre><pre>string(27) "Created or has been created"
</pre><pre>string(20) "Changed the category"
</pre><pre>string(10) "Meta title"
</pre><pre>string(23) "Translated the category"
</pre><pre>string(32) "Changed the category translation"
</pre><pre>string(28) "Category translation updated"
</pre><pre>string(23) "Category deletion error"
</pre><pre>string(51) "Deleted ID category or ID category has been deleted"
</pre><pre>string(16) "Category deleted"
</pre><pre>string(9) "profiler_"
</pre><pre>string(11) "No profiles"
</pre><pre>string(9) "Dashboard"
</pre><pre>string(25) "Custom fields constructor"
</pre><pre>string(11) "Fields list"
</pre><pre>string(13) "Group's list "
</pre><pre>string(15) "Categories list"
</pre><pre>string(13) "Create widget"
</pre><pre>string(15) "Template editor"
</pre><pre>string(14) "Events journal"
</pre><pre>string(6) "Backup"
</pre><pre>string(14) "Shop dashboard"
</pre><pre>string(14) "Order statuses"
</pre><pre>string(14) "Callbacks list"
</pre><pre>string(18) "Notifications list"
</pre><pre>string(21) "Notification statuses"
</pre><pre>string(5) "Other"
</pre><pre>string(18) "Products catalogue"
</pre><pre>string(13) "Produkts kits"
</pre><pre>string(16) "Users management"
</pre><pre>string(13) "List of users"
</pre><pre>string(12) "RBAC control"
</pre><pre>string(10) "Currencies"
</pre><pre>string(27) "Delivery methods (shipping)"
</pre><pre>string(15) "Payment methods"
</pre><pre>string(13) "Custom fields"
</pre><pre>string(16) "Delivery created"
</pre><pre>string(28) "Delivery method is not found"
</pre><pre>string(19) "No data transmitted"
</pre><pre>string(23) "Delivery method removed"
</pre><pre>string(15) "Positions saved"
</pre><pre>string(45) "A user with this email is already registered."
</pre><pre>string(10) "Created by"
</pre><pre>string(12) "User created"
</pre><pre>string(14) "User not found"
</pre><pre>string(15) "Members removed"
</pre><pre>string(40) "Certificate with this key already exists"
</pre><pre>string(23) "Cost of the certificate"
</pre><pre>string(22) "Certificate is created"
</pre><pre>string(27) "Certificate (s) removed (s)"
</pre><pre>string(46) "You have changed the status of the certificate"
</pre><pre>string(22) "The settings are saved"
</pre><pre>string(16) "Discount created"
</pre><pre>string(21) "Discounts are removed"
</pre><pre>string(14) "Banner created"
</pre><pre>string(25) "Banner could not be found"
</pre><pre>string(14) "Banner updated"
</pre><pre>string(14) "Banner removed"
</pre><pre>string(10) " language "
</pre><pre>string(16) "Position created"
</pre><pre>string(26) "Such status does not exist"
</pre><pre>string(26) "Default status was changed"
</pre><pre>string(29) "Callback's status was changed"
</pre><pre>string(28) "Positions saved successfully"
</pre><pre>string(19) "Callback is changed"
</pre><pre>string(20) "Callback was removed"
</pre><pre>string(21) "Callbacks was removed"
</pre><pre>string(31) "Unable to remove default status"
</pre><pre>string(18) "Status was removed"
</pre><pre>string(13) "Topic started"
</pre><pre>string(13) "Topic deleted"
</pre><pre>string(20) "Order status created"
</pre><pre>string(22) "Order Status not found"
</pre><pre>string(33) "Status and related orders removed"
</pre><pre>string(14) "Status removed"
</pre><pre>string(32) "Unable to remove the base status"
</pre><pre>string(43) "You did not ask for a set of main commodity"
</pre><pre>string(41) "You must attach the goods to create a set"
</pre><pre>string(34) "Kit with such goods already exists"
</pre><pre>string(11) "Kit created"
</pre><pre>string(21) "The kit was not found"
</pre><pre>string(44) "You did not ask for a set of main commodity "
</pre><pre>string(41) "Set (s) has been successfully removed (s)"
</pre><pre>string(16) "Property created"
</pre><pre>string(25) "The property is not found"
</pre><pre>string(31) "The list of properties is empty"
</pre><pre>string(25) "The property(ies) deleted"
</pre><pre>string(25) "Change saved successfully"
</pre><pre>string(30) "An additional field is created"
</pre><pre>string(15) "Field not found"
</pre><pre>string(16) "Field is removed"
</pre><pre>string(26) "This URL is already in use"
</pre><pre>string(13) "Brand created"
</pre><pre>string(15) "Brand not found"
</pre><pre>string(25) "Notification is not found"
</pre><pre>string(36) "Manager does not exist or is not set"
</pre><pre>string(20) "Notification updated"
</pre><pre>string(27) "Notification status updated"
</pre><pre>string(26) "User is notified by E-mail"
</pre><pre>string(12) "Uninstalling"
</pre><pre>string(20) "Order status changed"
</pre><pre>string(22) "Status pending created"
</pre><pre>string(24) "Status pending not found"
</pre><pre>string(13) "The amount of"
</pre><pre>string(13) "Amount before"
</pre><pre>string(16) "Discount updated"
</pre><pre>string(22) "refreshed successfully"
</pre><pre>string(27) "Cumulative discount removed"
</pre><pre>string(17) "Warehouse created"
</pre><pre>string(19) "Warehouse not found"
</pre><pre>string(19) "No data transferred"
</pre><pre>string(17) "Warehouse deleted"
</pre><pre>string(28) "The operation was successful"
</pre><pre>string(18) "Category not found"
</pre><pre>string(27) "This URL is already in use!"
</pre><pre>string(19) "Field Url is empty!"
</pre><pre>string(36) "The product was successfully created"
</pre><pre>string(17) "Product not found"
</pre><pre>string(25) "The specified URL is busy"
</pre><pre>string(35) "The product was successfully edited"
</pre><pre>string(13) "Price updated"
</pre><pre>string(6) "(copy)"
</pre><pre>string(31) "A copy was successfully created"
</pre><pre>string(25) "Payment method is created"
</pre><pre>string(28) "Payment method is not found."
</pre><pre>string(28) "Method of payment is removed"
</pre><pre>string(26) "Number of products on site"
</pre><pre>string(50) "Array of values for the number of products on site"
</pre><pre>string(40) "The number of items in the control panel"
</pre><pre>string(16) "Pictures Updated"
</pre><pre>string(16) "Currency created"
</pre><pre>string(18) "Currency not found"
</pre><pre>string(34) "Unable to remove the main currency"
</pre><pre>string(64) "Error. Currency used by other objects. Check the payment methods"
</pre><pre>string(77) "Error. The currency used in the products. Check the currency options products"
</pre><pre>string(29) "Currency successfully removed"
</pre><pre>string(53) "Conversion completed. Now the currency may be removed"
</pre><pre>string(14) "Prices updated"
</pre><pre>string(34) "There was no price for the upgrade"
</pre><pre>string(13) "Forward&nbsp;"
</pre><pre>string(10) "&nbsp;Back"
</pre><pre>string(15) "Order not found"
</pre><pre>string(20) "Order Status changed"
</pre><pre>string(18) "Orders are removed"
</pre><pre>string(32) "Payment status of orders changed"
</pre><pre>string(5) "Saved"
</pre><pre>string(47) "You can not delete the last item from the order"
</pre><pre>string(33) "Product is removed from the Order"
</pre><pre>string(35) "Very high price, please set smaller"
</pre><pre>string(15) "Product updated"
</pre><pre>string(32) "Item has been added to the order"
</pre><pre>string(27) "This product does not exist"
</pre><pre>string(30) "Order was successfully created"
</pre><pre>string(20) "User is not selected"
</pre><pre>string(31) "Delivery method is not selected"
</pre><pre>string(30) "Payment method is not selected"
</pre><pre>string(18) "Specified URL busy"
</pre><pre>string(16) "Category created"
</pre><pre>string(21) "Specified URL is busy"
</pre><pre>string(29) "Category deleted successfully"
</pre><pre>string(31) "Categories deleted successfully"
</pre><pre>string(29) "Failed to delete the category"
</pre><pre>string(22) "Category was not found"
</pre><pre>string(38) "The file has been successfully created"
</pre><pre>string(21) "Could not create file"
</pre><pre>string(29) "Could not find any properties"
</pre><pre>string(17) "You do not choose"
</pre><pre>string(19) "Export successfully"
</pre><pre>string(9) "ProductId"
</pre><pre>string(16) "CSV column name "
</pre><pre>string(18) "Multiple selection"
</pre><pre>string(20) "Show on product page"
</pre><pre>string(13) "Main property"
</pre><pre>string(23) "Show in product compare"
</pre><pre>string(14) "Show in filter"
</pre><pre>string(17) "Use in categories"
</pre><pre>string(19) "Banner text created"
</pre><pre>string(16) "Описание"
</pre><pre>string(10) "Start date"
</pre><pre>string(11) "Finish date"
</pre><pre>string(11) "Users group"
</pre><pre>string(5) "Login"
</pre><pre>string(3) "FIO"
</pre><pre>string(13) "Time register"
</pre><pre>string(13) "Sum purchases"
</pre><pre>string(13) "Custom object"
</pre><pre>string(21) "Custom required field"
</pre><pre>string(21) "Custom multiple field"
</pre><pre>string(20) "Custom posibble list"
</pre><pre>string(11) "Validations"
</pre><pre>string(19) "Custom active field"
</pre><pre>string(21) "Сustom private field"
</pre><pre>string(18) "Custom right field"
</pre>