<?php

$config = [
           'allowedDemodataTables' => [
                                       'content',
                                       'banners',
                                       'banners_i18n',
                                       'banner_image',
                                       'banner_image_i18n',
                                       'menus',
                                       'menus_data',
                                       'menu_translate',
                                       'mod_banner',
                                       'mod_banner_groups',
                                       'mod_banner_i18n',
                                       'shop_banners',
                                       'shop_banners_i18n',
                                       'shop_brands',
                                       'shop_brands_i18n',
                                       'shop_category',
                                       'shop_category_i18n',
                                       'shop_kit',
                                       'shop_kit_product',
                                       'shop_products',
                                       'shop_products_i18n',
                                       'shop_product_categories',
                                       'shop_product_images',
                                       'shop_product_properties',
                                       'shop_product_properties_categories',
                                       'shop_product_properties_data',
                                       'shop_product_properties_data_i18n',
                                       'shop_product_properties_i18n',
                                       'shop_product_property_value',
                                       'shop_product_property_value_i18n',
                                       'shop_product_variants',
                                       'shop_product_variants_i18n',
                                       'shop_sorting',
                                       'shop_sorting_i18n',
                                       'widgets',
                                       'route',
                                       'widget_i18n',
                                       'gallery_albums',
                                       'gallery_albums_i18n',
                                       'gallery_category',
                                       'gallery_category_i18n',
                                       'gallery_images',
                                       'gallery_images_i18n',
                                       'category',
                                       'category_translate',
                                      ],
          ];


return $config;