<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-27 at 13:06:50.
 */
class GalleryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Gallery
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Gallery;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Gallery::autoload
     * @todo   Implement testAutoload().
     */
    public function testAutoload() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gallery::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gallery::category
     * @todo   Implement testCategory().
     */
    public function testCategory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gallery::album
     * @todo   Implement testAlbum().
     */
    public function testAlbum() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gallery::thumbnails
     * @todo   Implement testThumbnails().
     */
    public function testThumbnails() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gallery::post_comment
     * @todo   Implement testPost_comment().
     */
    public function testPost_comment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gallery::create_albums_covers
     * @todo   Implement testCreate_albums_covers().
     */
    public function testCreate_albums_covers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gallery::_install
     * @todo   Implement test_install().
     */
    public function test_install() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gallery::_deinstall
     * @todo   Implement test_deinstall().
     */
    public function test_deinstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
