<?php

namespace template_manager\classes;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-09 at 16:38:48.
 */
class TComponentAssetManagerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TComponentAssetManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TComponentAssetManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers template_manager\classes\TComponentAssetManager::registerCss
     * @todo   Implement testRegisterCss().
     */
    public function testRegisterCss() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers template_manager\classes\TComponentAssetManager::registerScript
     * @todo   Implement testRegisterScript().
     */
    public function testRegisterScript() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers template_manager\classes\TComponentAssetManager::fetch
     * @todo   Implement testFetch().
     */
    public function testFetch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers template_manager\classes\TComponentAssetManager::display
     * @todo   Implement testDisplay().
     */
    public function testDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
