<?php

namespace template_manager\classes;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-09 at 16:39:03.
 */
class TemplateTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Template
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Template;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers template_manager\classes\Template::isValid
     * @todo   Implement testIsValid().
     */
    public function testIsValid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers template_manager\classes\Template::getComponent
     * @todo   Implement testGetComponent().
     */
    public function testGetComponent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers template_manager\classes\Template::getScreenshots
     * @todo   Implement testGetScreenshots().
     */
    public function testGetScreenshots() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
