<?php

namespace template_manager\classes;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-09 at 16:39:07.
 */
class TemplateManagerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TemplateManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TemplateManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers template_manager\classes\TemplateManager::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers template_manager\classes\TemplateManager::setTemplate
     * @todo   Implement testSetTemplate().
     */
    public function testSetTemplate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers template_manager\classes\TemplateManager::getCurentTemplate
     * @todo   Implement testGetCurentTemplate().
     */
    public function testGetCurentTemplate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers template_manager\classes\TemplateManager::listLocal
     * @todo   Implement testListLocal().
     */
    public function testListLocal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers template_manager\classes\TemplateManager::listRemote
     * @todo   Implement testListRemote().
     */
    public function testListRemote() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
