<?php

namespace Cart;

require_once realpath(dirname(__FILE__) . '/../../..') . '/enviroment.php';

doLogin();

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-13 at 13:12:44.
 */
class ApiTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Api
     */
    protected $object;
    protected $errorCallMethodResult;
    protected $ci;
    protected $productVarId;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new \Cart\Api;
        $this->errorCallMethodResult = json_encode(array('success' => false, 'errors' => true, 'message' => 'Method not found.'));
        
        $this->ci = & get_instance();
        $product = $this->ci->db->limit(1)->get('shop_product_variants')->row_array();
        $this->productVarId = $product['id'];
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Cart\Api::create
     * @todo   Implement testCreate().
     */
    public function testCreate() {
        $this->assertTrue($this->object->create() instanceof \Cart\Api);
    }

    /**
     * @covers Cart\Api::__call
     * @todo   Implement test__call().
     */
    public function test__call() {
        $this->assertEquals(NULL, $this->object->__call('create'));
        $this->assertJsonStringEqualsJsonString($this->errorCallMethodResult, $this->object->__call('notExistingMethod'));
    }

    /**
     * @covers Cart\Api::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // working        
    }

    /**
     * @covers Cart\Api::addProductByVariantId
     * @todo   Implement testAddProductByVariantId().
     */
    public function testAddProductByVariantId() {
//        $_GET['quantity'] = 3;

        var_dumps($this->object->addProductByVariantId($this->productVarId));
    }

    /**
     * @covers Cart\Api::addKit
     * @todo   Implement testAddKit().
     */
    public function testAddKit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\Api::sync
     * @todo   Implement testSync().
     */
    public function testSync() {
        var_dumps($this->object->sync());
    }

    /**
     * @covers Cart\Api::renderCart
     * @todo   Implement testRenderCart().
     */
    public function testRenderCart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\Api::get_kit_discount
     * @todo   Implement testGet_kit_discount().
     */
    public function testGet_kit_discount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\Api::getProductByVariantId
     * @todo   Implement testGetProductByVariantId().
     */
    public function testGetProductByVariantId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\Api::getKit
     * @todo   Implement testGetKit().
     */
    public function testGetKit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\Api::removeKit
     * @todo   Implement testRemoveKit().
     */
    public function testRemoveKit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\Api::removeProductByVariantId
     * @todo   Implement testRemoveProductByVariantId().
     */
    public function testRemoveProductByVariantId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\Api::removeAll
     * @todo   Implement testRemoveAll().
     */
    public function testRemoveAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\Api::getTotalItemsCount
     * @todo   Implement testGetTotalItemsCount().
     */
    public function testGetTotalItemsCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\Api::getPrice
     * @todo   Implement testGetPrice().
     */
    public function testGetPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\Api::getOriginPrice
     * @todo   Implement testGetOriginPrice().
     */
    public function testGetOriginPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\Api::setTotalPrice
     * @todo   Implement testSetTotalPrice().
     */
    public function testSetTotalPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\Api::getData
     * @todo   Implement testGetData().
     */
    public function testGetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
