<?php

namespace Cart;

require_once realpath(dirname(__FILE__) . '/../../..') . '/enviroment.php';

doLogin();

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-13 at 10:59:19.
 */
class BaseCartTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BaseCart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = \Cart\BaseCart::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @covers Cart\BaseCart::addItem
     * @todo   Implement testAddItem().
     */
    public function testAddItem() {
        
       $result = $this->object->addItem(array('instance' => 'SProducts', 'id' => 13381, 'quantity' => 1)); 
       $this->assertArrayHasKey('errors', $result);
       /*
       $result = $this->object->addItem(array('instance' => 'SProducts', 'id' => 892, 'quantity' => 2));
       $this->assertTrue($result['success']);
       
       $result = $this->object->addItem(array('instance' => 'ShopKit', 'id' => 1, 'quantity' => 2));
       $this->assertTrue($result['success']);
       
       $result = $this->object->addItem(array('instance' => 'ShopKit', 'id' => 1, 'quantity' => 1));
       $this->assertTrue($result['success']);
       
       $result = $this->object->addItem(array('instance' => 'SProducts', 'id' => 892, 'quantity' => 4));
        
        */
       
       
    }
    

    /**
     * @covers Cart\BaseCart::setQuantity
     * @todo   Implement testSetQuantity().
     */
    public function testSetQuantity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\BaseCart::setItemPrice
     * @todo   Implement testSetItemPrice().
     */
    public function testSetItemPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\BaseCart::removeItem
     * @todo   Implement testRemoveItem().
     */
    public function testRemoveItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\BaseCart::getTotalItems
     * @todo   Implement testGetTotalItems().
     */
    public function testGetTotalItems() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\BaseCart::removeAll
     * @todo   Implement testRemoveAll().
     */
    public function testRemoveAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\BaseCart::setTotalPrice
     * @todo   Implement testSetTotalPrice().
     */
    public function testSetTotalPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\BaseCart::getTotalPrice
     * @todo   Implement testGetTotalPrice().
     */
    public function testGetTotalPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\BaseCart::getOriginTotalPrice
     * @todo   Implement testGetOriginTotalPrice().
     */
    public function testGetOriginTotalPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\BaseCart::getItem
     * @todo   Implement testGetItem().
     */
    public function testGetItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\BaseCart::getItems
     * @todo   Implement testGetItems().
     */
    public function testGetItems() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\BaseCart::recountTotalPrice
     * @todo   Implement testRecountTotalPrice().
     */
    public function testRecountTotalPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\BaseCart::recountOriginTotalPrice
     * @todo   Implement testRecountOriginTotalPrice().
     */
    public function testRecountOriginTotalPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\BaseCart::delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
