<?php

//namespace Cart;
require_once realpath(dirname(__FILE__) . '/../../..') . '/enviroment.php';

require_once BASEPATH . '../application/modules/' . getModContDirName('shop') . '/shop/cart.php';

doLogin();

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-13 at 11:12:29.
 */
class CartTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Cart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, op_getUserProfileens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Cart();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Cart::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
//        $this->ass
//        $this->object->tplName = 'cart.tpl';
//        $result = $this->object->index();
//        var_dumps('');
//        var_dumps($result);
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::addProductByVariantId
     * @todo   Implement testAddProductByVariantId().
     */
    public function testAddProductByVariantId() {
        try {
            $this->object->addProductByVariantId(994);
        } catch (Exception $exc) {
            echo $exc->getMessage();
        }



        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
    }

    /**
     * @covers Cart::addKit
     * @todo   Implement testAddKit().
     */
    public function testAddKit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::api
     * @todo   Implement testApi().
     */
    public function testApi() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::getProductByVariantId
     * @todo   Implement testGetProductByVariantId().
     */
    public function testGetProductByVariantId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::getKit
     * @todo   Implement testGetKit().
     */
    public function testGetKit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::removeKit
     * @todo   Implement testRemoveKit().
     */
    public function testRemoveKit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::removeProductByVariantId
     * @todo   Implement testRemoveProductByVariantId().
     */
    public function testRemoveProductByVariantId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::removeAll
     * @todo   Implement testRemoveAll().
     */
    public function testRemoveAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::getTotalItemsCount
     * @todo   Implement testGetTotalItemsCount().
     */
    public function testGetTotalItemsCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::getPrice
     * @todo   Implement testGetPrice().
     */
    public function testGetPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::getOriginPrice
     * @todo   Implement testGetOriginPrice().
     */
    public function testGetOriginPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::setTotalPrice
     * @todo   Implement testSetTotalPrice().
     */
    public function testSetTotalPrice() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::getData
     * @todo   Implement testGetData().
     */
    public function testGetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::view
     * @todo   Implement testView().
     */
    public function testView() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::createCode
     * @todo   Implement testCreateCode().
     */
    public function testCreateCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::delivery_method_id_check
     * @todo   Implement testDelivery_method_id_check().
     */
    public function testDelivery_method_id_check() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart::clear
     * @todo   Implement testClear().
     */
    public function testClear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
