<?php

namespace Cart;

require_once realpath(dirname(__FILE__) . '/../../..') . '/enviroment.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-13 at 13:18:36.
 */
class SessionStorageTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SessionStorage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SessionStorage;
    }

//    private function _prepareData() {
//        $data1 = array(
//            'instance' => 'SProducts',
//            'id' => 211,
//        );
//        $data2 = array(
//            'instance' => 'ShopKit',
//            'id' => 16,
//            'quantity' => 5,
//        );
//        $this->object->setData($data1);
//        $this->object->setData($data2);
//    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Cart\SessionStorage::getData
     * @todo   Implement testGetData().
     */
//     * @dataProvider getDataByTermParametrs
    public function testGetData() {
        $result = (boolean) $this->object->getData();
        $this->assertFalse($result);

        $data1 = array(
            'instance' => 'SProducts',
            'id' => 211,
        );
//        $data2 = array(
//            'instance' => 'ShopKit',
//            'id' => 16,
//            'quantity' => 5,
//        );
        $this->object->setData($data1);
//        $this->object->setData($data2);
        
        $result = (boolean) $this->object->getData();
        $this->assertTrue($result);
        
//        $result = (boolean)$this->object->getData($term1, $term2);
//        $this->assertEquals($param, $result);
    }

    public function getDataByTermParametrs() {
        return array(
            array(null, null, false),
            array('SProducts', null, true),
            array(2, null, true),
//            array('SProducts'),
//            array('ShopKit'),
//            array(1,1),
//            array(1,80),
//            array(2,2),
//            array(2,80),
        );
    }

    /**
     * @covers Cart\SessionStorage::setData
     * @todo   Implement testSetData().
     */
    public function testSetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\SessionStorage::remove
     * @todo   Implement testRemove().
     */
    public function testRemove() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Cart\SessionStorage::exportToDB
     * @todo   Implement testExportToDB().
     */
    public function testExportToDB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
