<?php

require_once realpath(dirname(__FILE__) . '/../../../..') . '/enviroment.php';

doLogin();

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-27 at 13:30:04.
 */
class Wishlist_modelTest extends PHPUnit_Framework_TestCase {

    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Wishlist_model();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Wishlist_model::install
     */
    public function testInstall() {
        $this->assertTrue($this->object->install());
    }

    /**
     * @covers Wishlist_model::getSettings
     */
    public function testGetSettings() {
        $this->assertNotNull($this->object->getSettings(), 'Cant get Settings');
        $this->assertArrayHasKey('maxListName', $this->object->getSettings());
        $this->assertArrayHasKey('maxListsCount', $this->object->getSettings());
        $this->assertArrayHasKey('maxItemsCount', $this->object->getSettings());
        $this->assertArrayHasKey('maxCommentLenght', $this->object->getSettings());
        $this->assertArrayHasKey('maxDescLenght', $this->object->getSettings());
        $this->assertArrayHasKey('maxImageWidth', $this->object->getSettings());
        $this->assertArrayHasKey('maxImageHeight', $this->object->getSettings());
        $this->assertArrayHasKey('maxImageSize', $this->object->getSettings());
    }

    /**
     * @covers Wishlist_model::setSettings
     */
    public function testSetSettings() {
        $settings =
                array(
                    'maxListName' => 254,
                    'maxListsCount' => 10,
                    'maxItemsCount' => 100,
                    'maxCommentLenght' => 500,
                    'maxDescLenght' => 1000,
                    'maxImageWidth' => 150,
                    'maxImageSize' => 2000000,
                    'maxImageHeight' => 150);
        $this->assertTrue($this->object->setSettings($settings), 'Cant Set Settings');
    }

    /**
     * @covers Wishlist_model::getWishLists
     */
    public function testGetWishLists() {
        $this->assertInternalType('array', $this->object->getWishLists());
    }

    /**
     * @covers Wishlist_model::getAllUsers
     */
    public function testGetAllUsers() {
        $this->assertInternalType('array', $this->object->getAllUsers());
    }

    /**
     * @covers Wishlist_model::getUserByID
     */
    public function testGetUserByID() {
        $this->assertInternalType('array', $this->object->getUserByID($GLOBALS['userId']));
    }

    /**
     * @covers Wishlist_model::getWLsByUserId
     */
    public function testGetWLsByUserId() {
        $this->assertInternalType('array', $this->object->getWLsByUserId($GLOBALS['userId'], array('public', 'shared', 'private')));
    }

    /**
     * @covers Wishlist_model::createWishList
     */
    public function testCreateWishList() {
        $this->assertTrue($this->object->createWishList('test', $GLOBALS['userId'], 'shared'));
        $this->object->db
                ->where('title', 'test')
                ->set('hash', '1')
                ->update('mod_wish_list');
        $ID = $this->object->db->insert_id();
        return $ID;
    }

    /**
     * @covers Wishlist_model::updateWishListItem
     * @depends testCreateWishList
     */
    public function testUpdateWishListItem($id) {
//        $this->assertTrue($this->object->updateWishListItem('1031', $id, array()));
    }

    /**
     * @covers Wishlist_model::addItem
     * @depends testCreateWishList
     */
    public function testAddItem($id) {
        $this->assertTrue($this->object->addItem('1031', $id, '', 999999));
    }

    /**
     * @covers Wishlist_model::getUserWishList
     */
    public function testGetUserWishList() {
        $wishlist = new \wishlist\classes\ParentWishlist();
        $wishlist->createWishList($GLOBALS['userId'], 'test');
        $id = $this->object->db->insert_id();
        $this->assertInternalType('array', $this->object->getUserWishList($GLOBALS['userId'], $id, array('public', 'shared', 'private')));
//        $wishlist->deleteWL($id);
        return $id;
    }

    /**
     * @covers Wishlist_model::updateWishList
     * @depends testGetUserWishList
     */
    public function testUpdateWishList($id) {
        $this->assertFalse($this->object->updateWishList($id, array()));
    }

    /**
     * @covers Wishlist_model::getUserWishListByHash
     * @depends testGetUserWishList
     */
    public function testGetUserWishListByHash($id) {
        $hash = $this->object->db
                        ->where('id', $id)
                        ->get('mod_wish_list')
                        ->row()->hash;
        $this->assertInternalType('array', $this->object->GetUserWishListByHash($hash, array('public', 'shared', 'private')));
    }

    /**
     * @covers Wishlist_model::deleteItem
     * @depends testCreateWishList
     */
    public function testDeleteItem($id) {
        $this->assertTrue($this->object->deleteItem('1031', $id));
    }

    /**
     * @covers Wishlist_model::deleteItemsByIDs
     */
    public function testDeleteItemsByIDs() {
        $this->assertTrue($this->object->deleteItemsByIDs('1031'));
    }

    /**
     * @covers Wishlist_model::getUserWishListsByID
     */
    public function testGetUserWishListsByID() {
        $this->assertInternalType('array', $this->object->getUserWishListsByID($GLOBALS['userId'], array('public', 'shared', 'private')));
    }

    /**
     * @covers Wishlist_model::delWishListById
     * @depends testCreateWishList
     */
    public function testDelWishListById($id) {
        $this->assertTrue($this->object->delWishListById($id));
    }

    /**
     * @covers Wishlist_model::delWishListProductsByWLId
     * @depends testCreateWishList
     */
    public function testDelWishListProductsByWLId($id) {
        $this->assertTrue($this->object->delWishListProductsByWLId($id));
    }

    /**
     * @covers Wishlist_model::getUserWishProducts
     * @depends testCreateWishList
     */
    public function testGetUserWishProducts() {
        $this->assertInternalType('array', $this->object->getUserWishProducts($GLOBALS['userId']));
    }

    /**
     * @covers Wishlist_model::getAllUserWLs
     * @depends testCreateWishList
     */
    public function testGetAllUserWLs() {
        $this->assertInternalType('array', $this->object->getAllUserWLs($GLOBALS['userId']));
    }

    /**
     * @covers Wishlist_model::getMostPopularProducts
     */
    public function testGetMostPopularProducts() {
        $this->assertInternalType('array', $this->object->getMostPopularProducts());
    }

    /**
     * @covers Wishlist_model::insertWishList
     */
    public function testInsertWishList() {
        $this->assertTrue($this->object->insertWishList('test', 'shared', $GLOBALS['userId']));
    }

    /**
     * @covers Wishlist_model::updateWishListItemsComments
     * @depends testCreateWishList
     */
    public function testUpdateWishListItemsComments($id) {
        $this->assertFalse($this->object->insertWishList($id, array()));
    }

    /**
     * @covers Wishlist_model::insertUser
     */
    public function testInsertUser() {
        $this->assertTrue($this->object->insertUser(999999, '', '', 'test'));
        $this->assertFalse($this->object->insertUser(999999, '', '', 'test'));
        $id = $this->object->db->insert_id();
        return $id;
    }

    /**
     * @covers Wishlist_model::createUserIfNotExist
     */
    public function testCreateUserIfNotExist() {
        $this->assertTrue($this->object->createUserIfNotExist(888888));
        $this->assertFalse($this->object->createUserIfNotExist(888888));
    }

    /**
     * @covers Wishlist_model::updateUser
     */
    public function testUpdateUser() {
        $this->assertTrue($this->object->updateUser($GLOBALS['userId'], 'test', '111111', 'desc'));
    }

    /**
     * @covers Wishlist_model::getUserWishListCount
     */
    public function testGetUserWishListCount() {
        $this->assertInternalType('int', $this->object->getUserWishListCount(999999));
    }

    /**
     * @covers Wishlist_model::getUserWishListItemsCount
     */
    public function testGetUserWishListItemsCount() {
        $this->assertInternalType('int', $this->object->getUserWishListItemsCount(999999));
    }

    /**
     * @covers Wishlist_model::addReview
     */
    public function testAddReview() {
        $this->assertTrue($this->object->addReview(1), 'Cant add review');
    }

    /**
     * @covers Wishlist_model::getMostViewedWishLists
     */
    public function testGetMostViewedWishLists() {
        $this->assertInternalType('array', $this->object->getMostViewedWishLists());
    }

    /**
     * @covers Wishlist_model::setUserImage
     */
    public function testSetUserImage() {
        $this->assertTrue($this->object->setUserImage(999999, '111.png'));
    }

    /**
     * @covers Wishlist_model::deinstall
     */
    public function testDeinstall() {
        $this->assertTrue($this->object->deinstall());
        $this->object->install();
    }

}
