<?php

require_once realpath(dirname(__FILE__) . '/../../..') . '/enviroment.php';

doLogin();
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-03 at 13:11:06.
 */
class AdminTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Admin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
        var_dump(APPPATH.'modules/mod_dicount/admin.php');
        $this->object = new Admin();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Admin::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Admin::create
     * @todo   Implement testCreate().
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Admin::edit
     * @todo   Implement testEdit().
     */
    public function testEdit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Admin::ajaxChangeActive
     * @todo   Implement testAjaxChangeActive().
     */
    public function testAjaxChangeActive() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Admin::ajaxDeleteDiscount
     * @todo   Implement testAjaxDeleteDiscount().
     */
    public function testAjaxDeleteDiscount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Admin::generateDiscountKey
     * @todo   Implement testGenerateDiscountKey().
     */
    public function testGenerateDiscountKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Admin::autoCompliteUsers
     * @todo   Implement testAutoCompliteUsers().
     */
    public function testAutoCompliteUsers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Admin::autoCompliteProducts
     * @todo   Implement testAutoCompliteProducts().
     */
    public function testAutoCompliteProducts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Admin::saveQueryToSession
     * @todo   Implement testSaveQueryToSession().
     */
    public function testSaveQueryToSession() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
