<?php return array( 
  array(
     'identifier' => 'content',
     'text' =>  lang("Страницы", "admin_menu"),
     'link' => '',
     'class' => '',
     'id' => '',
     'pjax' => '',
     'icon' => 'icon-align-justify',
     'divider' => false,
     'callback' => '',
     'subMenu' => 
    array( 
      array(
         'identifier' => 'create_page',
         'text' =>  lang("Создать страницу", "admin_menu"),
         'link' => '/admin/pages',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'articles_list',
         'text' =>  lang("Список страниц", "admin_menu"),
         'link' => '/admin/pages/GetPagesByCategory',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => '',
         'text' =>  lang("Конструктор полей", "admin_menu"),
         'link' => '/admin/components/cp/cfcm/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ),
    ),
  ), 
  array(
     'identifier' => 'categories',
     'text' =>  lang("Категории", "admin_menu"),
     'link' => '',
     'class' => '',
     'id' => '',
     'pjax' => '',
     'icon' => 'icon-list',
     'divider' => false,
     'callback' => '',
     'subMenu' => 
    array( 
      array(
         'identifier' => 'new_category',
         'text' =>  lang("Создать категорию", "admin_menu"),
         'link' => '/admin/categories/create_form',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'categories_list',
         'text' =>  lang("Список категорий", "admin_menu"),
         'link' => '/admin/categories/cat_list',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ),
    ),
  ), 
  array(
     'identifier' => 'modules',
     'text' =>  lang("Модули", "admin_menu"),
     'link' => '',
     'class' => '',
     'id' => '',
     'pjax' => '',
     'icon' => 'icon-circle-arrow-down',
     'divider' => false,
     'callback' => '',
     'subMenu' => 
    array( 
      array(
         'identifier' => 'all_modules',
         'text' =>  lang("Все модули", "admin_menu"),
         'link' => '/admin/components/modules_table',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ),
    ),
  ), 
  array(
     'identifier' => 'widgets',
     'text' =>  lang("Виджеты", "admin_menu"),
     'link' => '',
     'class' => '',
     'id' => '',
     'pjax' => '',
     'icon' => 'icon-th',
     'divider' => false,
     'callback' => '',
     'subMenu' => 
    array( 
      array(
         'identifier' => 'create_widget',
         'text' =>  lang("Создать виджет", "admin_menu"),
         'link' => '/admin/widgets_manager/create_tpl',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'widgets_list',
         'text' =>  lang("Список виджетов", "admin_menu"),
         'link' => '/admin/widgets_manager',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ),
    ),
  ), 
  array(
     'identifier' => 'system',
     'text' =>  lang("Система", "admin_menu"),
     'link' => '',
     'class' => '',
     'id' => '',
     'pjax' => '',
     'icon' => 'icon-hdd',
     'divider' => false,
     'callback' => '',
     'subMenu' => 
    array( 
      array(
         'identifier' => 'global_settings',
         'text' =>  lang("Глобальные настройки", "admin_menu"),
         'link' => '/admin/settings',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'template_editor',
         'text' =>  lang("Редактор шаблонов", "admin_menu"),
         'link' => '/admin/components/cp/template_editor',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'languages',
         'text' =>  lang("Языки", "admin_menu"),
         'link' => '/admin/languages',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'events_journal',
         'text' =>  lang("Журнал событий", "admin_menu"),
         'link' => '/admin/admin_logs',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'backup',
         'text' =>  lang("Резервное копирование", "admin_menu"),
         'link' => '/admin/backup',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'role_list',
         'text' =>  lang("Управление правами доступа", "admin_menu"),
         'link' => '/admin/rbac/roleList',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'custom_fields',
         'text' =>  lang("Очистить кеш", "admin_menu"),
         'link' => '',
         'class' => '',
         'id' => 'clearAllCache',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ),
    ),
  ),
);