<?php return array( 
  array(
     'identifier' => 'orders',
     'text' =>  lang("Orders", "admin_menu"),
     'link' => '',
     'class' => '',
     'id' => '',
     'pjax' => '',
     'icon' => 'icon-shopping-cart',
     'divider' => false,
     'callback' => 'getNewOCNSum',
     'subMenu' => 
    array( 
      array(
         'identifier' => 'orders_list',
         'text' =>  lang("Orders list", "admin_menu"),
         'link' => '/admin/components/run/shop/orders/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => 'getNewOrdersCount',
      ), 
      array(
         'identifier' => 'order_statuses',
         'text' =>  lang("Order statuses", "admin_menu"),
         'link' => '/admin/components/run/shop/orderstatuses',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'callbacks_list',
         'text' =>  lang("Callbacks list", "admin_menu"),
         'link' => '/admin/components/run/shop/callbacks',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => 'getNewCallbacksCount',
      ), 
      array(
         'identifier' => 'callback_statuses',
         'text' =>  lang("Callback statuses", "admin_menu"),
         'link' => '/admin/components/run/shop/callbacks/statuses',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'callback_themes',
         'text' =>  lang("Callback themes", "admin_menu"),
         'link' => '/admin/components/run/shop/callbacks/themes',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'notifications_list',
         'text' =>  lang("Notifications list", "admin_menu"),
         'link' => '/admin/components/run/shop/notifications',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => 'getNewNotificationsCount',
      ), 
      array(
         'identifier' => 'notification_statuses',
         'text' =>  lang("Notification statuses", "admin_menu"),
         'link' => '/admin/components/run/shop/notificationstatuses/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ),
    ),
  ), 
  array(
     'identifier' => 'products_catalogue',
     'text' =>  lang("Products catalogue", "admin_menu"),
     'link' => '',
     'class' => '',
     'id' => '',
     'pjax' => '',
     'icon' => 'icon-list-alt',
     'divider' => false,
     'callback' => '',
     'subMenu' => 
    array( 
      array(
         'identifier' => 'product_categories',
         'text' =>  lang("Product categories", "admin_menu"),
         'link' => '/admin/components/run/shop/categories/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'create_category',
         'text' =>  lang("Create category", "admin_menu"),
         'link' => '/admin/components/run/shop/categories/create',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'products_list',
         'text' =>  lang("Products list", "admin_menu"),
         'link' => '/admin/components/run/shop/search/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'create_product',
         'text' =>  lang("Create product", "admin_menu"),
         'link' => '/admin/components/run/shop/products/create',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'produkts_kits',
         'text' =>  lang("Produkts kits", "admin_menu"),
         'link' => '/admin/components/run/shop/kits/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'products_without_images',
         'text' =>  lang("Products without images", "admin_menu"),
         'link' => '/admin/components/run/shop/search?WithoutImages=1',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'brands',
         'text' =>  lang("Brands", "admin_menu"),
         'link' => '/admin/components/run/shop/brands/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'create_brand',
         'text' =>  lang("Create brand", "admin_menu"),
         'link' => '/admin/components/run/shop/brands/create',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'products_properties',
         'text' =>  lang("Products properties", "admin_menu"),
         'link' => '/admin/components/run/shop/properties/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'create_property',
         'text' =>  lang("Create property", "admin_menu"),
         'link' => '/admin/components/run/shop/properties/create',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ),
    ),
  ), 
  array(
     'identifier' => 'users_management',
     'text' =>  lang("Users management", "admin_menu"),
     'link' => '',
     'class' => '',
     'id' => '',
     'pjax' => '',
     'icon' => 'icon-user',
     'divider' => false,
     'callback' => '',
     'subMenu' => 
    array( 
      array(
         'identifier' => 'list_of_users',
         'text' =>  lang("List of users", "admin_menu"),
         'link' => '/admin/components/run/shop/users/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'rbac_control',
         'text' =>  lang("RBAC control", "admin_menu"),
         'link' => '/admin/rbac/roleList',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ),
    ),
  ), 
  array(
     'identifier' => 'content',
     'text' =>  lang("Content", "admin_menu"),
     'link' => '',
     'class' => '',
     'id' => '',
     'pjax' => '',
     'icon' => 'icon-align-justify',
     'divider' => false,
     'callback' => '',
     'subMenu' => 
    array( 
      array(
         'identifier' => 'create_page',
         'text' =>  lang("Create page", "admin_menu"),
         'link' => '/admin/pages',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'articles_list',
         'text' =>  lang("Articles list", "admin_menu"),
         'link' => '/admin/pages/GetPagesByCategory',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'create_category',
         'text' =>  lang("Create category", "admin_menu"),
         'link' => '/admin/categories/create_form',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'categories_list',
         'text' =>  lang("Categories list", "admin_menu"),
         'link' => '/admin/categories/cat_list',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'fields_list',
         'text' =>  lang("Fields list", "admin_menu"),
         'link' => '/admin/components/cp/cfcm/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'group\'s_list_',
         'text' =>  lang("Groups list ", "admin_menu"),
         'link' => '/admin/components/cp/cfcm/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ),
    ),
  ), 
  array(
     'identifier' => 'modules',
     'text' =>  lang("Modules", "admin_menu"),
     'link' => '',
     'class' => '',
     'id' => '',
     'pjax' => '',
     'icon' => 'icon-circle-arrow-down',
     'divider' => false,
     'callback' => '',
     'subMenu' => 
    array( 
      array(
         'identifier' => 'all_modules',
         'text' =>  lang("All modules", "admin_menu"),
         'link' => '/admin/components/modules_table',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ),
    ),
  ), 
  array(
     'identifier' => 'statistics',
     'text' =>  lang("Statistics", "admin_menu"),
     'link' => '',
     'class' => '',
     'id' => '',
     'pjax' => '',
     'icon' => 'icon-statistic',
     'divider' => false,
     'callback' => '',
     'subMenu' => 
    array( 
      array(
         'identifier' => 'statistics_orders',
         'text' =>  lang("Orders", "admin_menu"),
         'link' => '/admin/components/cp/mod_stats/orders/charts',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'statistics_users',
         'text' =>  lang("Users", "admin_menu"),
         'link' => '/admin/components/cp/mod_stats/users/online',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'statistics_products',
         'text' =>  lang("Products", "admin_menu"),
         'link' => '/admin/components/cp/mod_stats/products/categories',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'statistics_categories',
         'text' =>  lang("Categories", "admin_menu"),
         'link' => '/admin/components/cp/mod_stats/categories/attendance',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'statistics_search',
         'text' =>  lang("Search", "admin_menu"),
         'link' => '/admin/components/cp/mod_stats/search/keywords',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ),
    ),
  ), 
  array(
     'identifier' => 'settings',
     'text' =>  lang("Settings", "admin_menu"),
     'link' => '',
     'class' => '',
     'id' => '',
     'pjax' => '',
     'icon' => 'icon-cog',
     'divider' => false,
     'callback' => '',
     'subMenu' => 
    array( 
      array(
         'identifier' => 'global_settings',
         'text' =>  lang("Global settings", "admin_menu"),
         'link' => '/admin/settings',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'shop_settings',
         'text' =>  lang("Shop settings", "admin_menu"),
         'link' => '/admin/components/run/shop/settings',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'currencies',
         'text' =>  lang("Currencies", "admin_menu"),
         'link' => '/admin/components/run/shop/currencies',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'delivery_methods_(shipping)',
         'text' =>  lang("Delivery methods (shipping)", "admin_menu"),
         'link' => '/admin/components/run/shop/deliverymethods/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'payment_methods',
         'text' =>  lang("Payment methods", "admin_menu"),
         'link' => '/admin/components/run/shop/paymentmethods/index',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'widgets',
         'text' =>  lang("Widgets", "admin_menu"),
         'link' => '/admin/widgets_manager',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'custom_fields',
         'text' =>  lang("Custom fields", "admin_menu"),
         'link' => '/admin/components/run/shop/customfields',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'template_manager',
         'text' =>  lang("Template editor", "admin_menu"),
         'link' => '/admin/components/cp/template_editor',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'languages',
         'text' =>  lang("Languages", "admin_menu"),
         'link' => '/admin/languages',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'events_journal',
         'text' =>  lang("Events journal", "admin_menu"),
         'link' => '/admin/admin_logs',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'backup',
         'text' =>  lang("Backup", "admin_menu"),
         'link' => '/admin/backup',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'roles_list',
         'text' =>  lang("Roles list", "admin_menu"),
         'link' => '/admin/rbac/roleList',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'system_update',
         'text' =>  lang("System update", "admin_menu"),
         'link' => '/admin/sys_update',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ), 
      array(
         'identifier' => 'system_information',
         'text' =>  lang("System information", "admin_menu"),
         'link' => '/admin/sys_info',
         'class' => '',
         'id' => '',
         'pjax' => '',
         'icon' => '',
         'divider' => true,
         'callback' => '',
      ), 
      array(
         'identifier' => 'custom_fields',
         'text' =>  lang("Clear cache", "admin_menu"),
         'link' => '',
         'class' => '',
         'id' => 'clearAllCache',
         'pjax' => '',
         'icon' => '',
         'divider' => false,
         'callback' => '',
      ),
    ),
  ),
);